### PR TITLE
Revert "Remove unused npx binary"

### PR DESCRIPTION
**Pull request by MylesBorins**
This reverts commit f019a248a67e8c46dbe41bf31f4818c5ca2138bf.

Git Bash on Windows still uses this file. Removing it broke
the windows MSI builds in Node.js infrastructure. Unless we
absolutely need to remove this I think it is worth keeping
around

### CODE REVIEW

**Review by darcyclarke — APPROVED** [review]
✅ LGTM

**Comment by ruyadorno** [comment]
we should also fix the permission of this file! which was the original intent of #1792

**Comment by MylesBorins** [comment]
@ruyadorno I've floated your patch

**Comment by ruyadorno** [comment]
we just merged it 😊 it's out in `v7.0.0-rc.3`

**Pull request closed without merging**
