### PR TITLE
docs: add missing bugs key in package-json.md

### PR DESCRIPTION
**Pull request by airscripts**
In this part of the documentation, the root key `bugs` was missing.   
This leads to confusion since inside this markdown, everything comes explained with the whole object and not only the nested one.  
Same thing happens for other release branches.

## References

I haven't found any references about this.

### CODE REVIEW

**Comment by wraithgar** [comment]
Can you rebase this against `latest`?

**Comment by airscripts** [comment]
> Can you rebase this against `latest`?

Rebased against `latest` and reworded even the commit changing `refactor` with `docs`.  
Let me know if something else is needed.

**Comment by wraithgar** [comment]
You'll need to drop the v9 commit that got brought over

**Comment by airscripts** [comment]
> You'll need to drop the v9 commit that got brought over

I think we are good, now.

**Review by wraithgar — APPROVED** [review]

**Pull request merged**
