### PR TITLE
chore: check less stuff into node_modules

### PR DESCRIPTION
**Pull request by isaacs**
We bundle our deps, but we don't need to bundle docs, changelogs,
editorconfigs, test coverage reports, .github workflow definitions,
lint configurations, and all the rest, which we never use.

This cuts about 10% off of our publish artifact file size.

```
$ ls -laF npm-7.16.0-*.tgz
-rw-r--r--  1 isaacs  staff  7174497 Jun  3 13:01 npm-7.16.0-release-next.tgz
-rw-r--r--  1 isaacs  staff  6782377 Jun  3 13:00 npm-7.16.0-trim-node-modules.tgz

$ ls -laF npm-7.16.0-*.tar
-rw-r--r--  1 isaacs  staff  19020288 Jun  3 13:01 npm-7.16.0-release-next.tar
-rw-r--r--  1 isaacs  staff  17474048 Jun  3 13:00 npm-7.16.0-trim-node-modules.tar
```

### CODE REVIEW

**Comment by nlf** [comment]
if we only gitignore them, then won't running `node . run resetdeps` put the files back and end up with them being bundled and packed into the tarball anyway?

**Comment by isaacs** [comment]
> if we only gitignore them, then won't running `node . run resetdeps` put the files back and end up with them being bundled and packed into the tarball anyway?

No, because `resetdeps` deletes and then checks out the `node_modules` folder.  When we install something new, yes, it'll put the ignored files there, but we won't check them in, so `resetdeps` will remove them.

There is a hazard, I suppose, that we install a new dep, and do a release from the same machine before ever running `resetdeps`, but I don't think that's a very big hazard, tbh.

**Comment by nlf** [comment]
agreed it's pretty minimal. 

we should probably update the release process wiki page with a note to always run resetdeps before publishing just to give us a reminder

**Review by nlf — APPROVED** [review]

**Comment by wraithgar** [comment]
> we should probably update the release process wiki page with a note to always run resetdeps before publishing just to give us a reminder

Should this be added to `make publish`?

**Comment by nlf** [comment]
> > we should probably update the release process wiki page with a note to always run resetdeps before publishing just to give us a reminder
> 
> Should this be added to `make publish`?

that feels like a good idea. we do a prune immediately before the publish, so i think if we did the resetdeps right before the prune we wouldn't have to worry about doing this step manually and we'd still catch when there are uncommitted changes to node_modules

**Comment by isaacs** [comment]
> > we should probably update the release process wiki page with a note to always run resetdeps before publishing just to give us a reminder
> 
> Should this be added to `make publish`?

Yes, putting steps in code is always better than putting them in docs.

**Review by midudev — APPROVED** [review]

**Pull request merged**
