### PR TITLE
fix: exit codes in node v20

### LINKED ISSUE #6399: [BUG] exit codes not being set properly in node v20
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Running [`npm audit`](https://docs.npmjs.com/cli/v9/commands/npm-audit) (seemingly) always exists with a 0 exit code, even if a vulnerability is found (with a severity higher than configured by the [`audit-level`](https://docs.npmjs.com/cli/v9/using-npm/config#audit-level)).

In contrast, `npm@8.15.0` (`node@18.7.0`) exits with a 1 if a vulnerability is found (with a severity higher than configured by the [`audit-level`](https://docs.npmjs.com/cli/v9/using-npm/config#audit-level)).

### Expected Behavior

Per the [Exit Code section](https://docs.npmjs.com/cli/v9/commands/npm-audit#exit-code):

> [...]
>
> If vulnerabilities were found the exit code will depend on the [`audit-level` config](https://docs.npmjs.com/cli/v9/using-npm/config#audit-level).

### Steps To Reproduce

1. Clone https://github.com/ericcornelissen/shescape/tree/dbaa0fd36af4fd0439af87548ce710468f25cb18
2. Run `npm audit`
3. Observe a warning for (at least) the high severity vulnerability GHSA-9c47-m6qq-7p4h
4. Run `echo $?`
5. Observe a `0` being printed

### Environment

- npm: 9.6.5
- Node.js: v20.0.0
- OS Name: Ubuntu 22.04.2 LTS
- System Model Name: _custom_
- npm config:
```ini
; "user" config from ~/.npmrc

update-notifier = false 

; "project" config from ~/workspace/shescape/.npmrc

lockfile-version = "3" 
save-exact = true 
save-prefix = "" 

; node bin location = ~/.nvm/versions/node/v20.0.0/bin/node
; node version = v20.0.0
; npm local prefix = ~/Documents/workspace/shescape
; npm version = 9.6.5
; cwd = ~/Documents/workspace/shescape
; HOME = ~
; Run `npm config ls -l` to show all defaults.
```

### PR DESCRIPTION
**Pull request by MichaelBitard**
Fixes #6399

Properly this time I hope :)

### CODE REVIEW

**Comment by wraithgar** [comment]
This subtly changes the behavior of when npm shows the "A complete log of this run can be found".  Because this PR sets the `exitCode` variable no matter what, instead of only if we had a specific error, it will now show up during an `npm audit` where vulnerabilities are found.  This is not what we want.

```
showLogFileError = (hasLoadedNpm && npm.silent) || noLogMessage
    ? false
    : !!exitCode
```

I think we have to leave `exitCode` undefined until we're ready to send it to `process.exit` and only then do we override it with `process.exitCode` if the `exitCode` variable is still undefined.

**Comment by MichaelBitard** [comment]
I added a noLogMessage to true when something goes wrong, we can suppose the error message has already been printed.

> I think we have to leave exitCode undefined until we're ready to send it to process.exit and only then do we override it with process.exitCode if the exitCode variable is still undefined.

I'm not sure to understand what it means.

If something set process.exitCode to something other than 0, that means the script failed at some point, and we should exit our process with an exitCode different than 0 rigth?

**Comment by wraithgar** [comment]
> If something set process.exitCode to something other than 0, that means the script failed at some point, and we should exit our process with an exitCode different than 0 rigth?

Correct, but we can't set our `exitCode` *variable* yet because that's doing some heavy lifting later on to determine if we need to show the extra logging message.  Typically if a command sets exitCode but doesn't throw, that message isn't shown.  Think of when you type `npm foo`, which isn't a command. You get an exit code of 1 but you don't get a message saying where to view the log of the run.  That extra message is reserved for when a command throws an error.  It's a subtle difference in signals from commands.


So, we have to wait till we call `process.exit` to see if we want to use `exitCode` or `process.exitCode`

**Comment by MichaelBitard** [comment]
Ok I think I understand, what I pushed after fixes these cases I think.
If not I'll have to think of another way of fixing this

**Review by wraithgar — APPROVED** [review]

**Comment by wraithgar** [comment]
Yep, you got there a different way by altering the other variable accordingly.  It works, and smoke tests still pass.  We'll add node 20 to our CI soon and cover any other holes soon hopefully.

**Pull request merged**
