### PR TITLE
[Docs] Add missing metadata in page “using-npm/semver” to fix broken links and nav

### PR DESCRIPTION
**Pull request by tripu**
**Problem:** there have been a number of broken links in [`docs.npmjs.com`](https://docs.npmjs.com/) for quite some time now. At least hyperlinks to section _Using npm / semver_ are broken.

Examples: visit [`docs.npmjs.com/configuring-npm/package-json`](https://docs.npmjs.com/configuring-npm/package-json.html#dependencies) and on your browser find the string `See semver`; there are 3 instances, all of them linking to [`docs.npmjs.com/using-npm/semver`](https://docs.npmjs.com/using-npm/semver), which does not exist.

A related outstanding issue (I believe) is that such subsection (_semver_) [does _not_ appear in the index page of section _Using npm_](https://docs.npmjs.com/cli-documentation/using-npm).

---

**Solution:** after digging a bit in the docs and how they are built, I think the cause may be that this specific page is lacking some metadata at the beginning. Because of that, the page is not generated, indexed and/or copied to the output dir. After changing this, Gatsby seems to be serving the page OK, and it appears in the nav sidebar element.

### CODE REVIEW

**Comment by tripu** [comment]
I just committed a small change in one of the Tap tests&nbsp;&mdash;&nbsp;the one checking documentation for _semver_.  
I think this issue originated in #274.

Tests pass now.  
This is ready for review.

**Comment by tripu** [comment]
@isaacs, am I missing any step here for the team to be able to review the PR?  
Cheers.

**Review by ruyadorno — APPROVED** [review]

**Comment by ruyadorno** [comment]
Awesome finding! 🙌 Thank you so much for the fix @tripu!

**Review by turan3548 — COMMENTED** [review]
Pıroje takıpcıkazan

**Comment by tripu** [comment]
Excuse me, I'm not familiar with your workflow: when will this be deployed to [`docs.npmjs.com`](https://docs.npmjs.com/)?

This change does not show there yet, and I was wondering.

**Pull request closed without merging**
