### PR TITLE
Release 6.13.5

### PR DESCRIPTION
**Pull request by ruyadorno**
### BUG FIXES

* [`fd0a802ec`](https://github.com/npm/cli/commit/fd0a802ec468ec7b98d6c15934c355fef0e7ff60) [#550](https://github.com/npm/cli/pull/550) Fix cache location for `npm ci` ([@zhenyavinogradov](https://github.com/zhenyavinogradov))
* [`4b30f3cca`](https://github.com/npm/cli/commit/4b30f3ccaebf50d6ab3bad130ff94827c017cc16) [#648](https://github.com/npm/cli/pull/648) fix(version): using 'allow-same-version', git commit --allow-empty and git tag -f ([@rhengles](https://github.com/rhengles))

### TESTING

* [`e16f68d30`](https://github.com/npm/cli/commit/e16f68d30d59ce1ddde9fe62f7681b2c07fce84d) test(ci): add failing cache config test ([@ruyadorno](https://github.com/ruyadorno))
* [`3f009fbf2`](https://github.com/npm/cli/commit/3f009fbf2c42f68c5127efecc6e22db105a74fe0) [#659](https://github.com/npm/cli/pull/659) test: fix bin-overwriting test on Windows ([@isaacs](https://github.com/isaacs))
* [`43ae0791f`](https://github.com/npm/cli/commit/43ae0791f74f68e02850201a64a6af693657b241) [#601](https://github.com/npm/cli/pull/601) ci: Allow builds to run even if one fails ([@XhmikosR](https://github.com/XhmikosR))
* [`4a669bee4`](https://github.com/npm/cli/commit/4a669bee4ac54c70adc6979d45cd0605b6dc33fd) [#603](https://github.com/npm/cli/pull/603) Remove the unused appveyor.yml ([@XhmikosR](https://github.com/XhmikosR))
* [`9295046ac`](https://github.com/npm/cli/commit/9295046ac92bbe82f4d84e1ec90cc81d3b80bfc7) [#600](https://github.com/npm/cli/pull/600) ci: switch to `actions/checkout@v2` ([@XhmikosR](https://github.com/XhmikosR))

### DOCUMENTATION

* [`f2d770ac7`](https://github.com/npm/cli/commit/f2d770ac768ea84867772b90a3c9acbdd0c1cb6a) [#569](https://github.com/npm/cli/pull/569) fix netlify publish path config ([@claudiahdz](https://github.com/claudiahdz))
* [`462cf0983`](https://github.com/npm/cli/commit/462cf0983dbc18a3d93f77212ca69f878060b2ec) [#627](https://github.com/npm/cli/pull/627) update gatsby dependencies ([@felixonmars](https://github.com/felixonmars))
* [`6fb5dbb72`](https://github.com/npm/cli/commit/6fb5dbb7213c4c050c9a47a7d5131447b8b7dcc8) [#532](https://github.com/npm/cli/pull/532) docs: clarify usage of global prefix ([@jgehrcke](https://github.com/jgehrcke))

### CODE REVIEW

**Comment by npm-deploy-user** [comment]
<table>
    <thead>
      <tr>
        <th></th>
        <th colspan="3">angular-quickstart</th>
<th colspan="3">app-large</th>
<th colspan="3">app-medium</th>
<th colspan="3">ember-quickstart</th>
<th colspan="3">react-app</th>
      </tr>
      <tr>
        <th></th>
        <th>prev</th>
<th>current</th>
<th>status</th>
<th>prev</th>
<th>current</th>
<th>status</th>
<th>prev</th>
<th>current</th>
<th>status</th>
<th>prev</th>
<th>current</th>
<th>status</th>
<th>prev</th>
<th>current</th>
<th>status</th>
      </tr>
    </thead>
    <tbody>
      <tr>
<td>initial install</td>
<td>38.3s</td>
<td>39.8s</td><td>✅🐌</td>
<td>36.7s</td>
<td>37.8s</td><td>✅🐌</td>
<td>32.4s</td>
<td>33.5s</td><td>✅🐌</td>
<td>26.3s</td>
<td>26.6s</td><td>✅🐌</td>
<td>30.6s</td>
<td>31.8s</td><td>✅🐌</td>
</tr>
<tr>
<td>repeat install</td>
<td>8.7s</td>
<td>9.2s</td><td>✅🐌</td>
<td>8.9s</td>
<td>8.3s</td><td>✅</td>
<td>8s</td>
<td>8.5s</td><td>✅🐌</td>
<td>6.9s</td>
<td>7.5s</td><td>✅🐌</td>
<td>8.4s</td>
<td>9s</td><td>✅🐌</td>
</tr>
<tr>
<td>with warm cache</td>
<td>29.1s</td>
<td>30.5s</td><td>✅🐌</td>
<td>31.7s</td>
<td>32.7s</td><td>✅🐌</td>
<td>27.2s</td>
<td>29.1s</td><td>✅🐌</td>
<td>22.4s</td>
<td>23.7s</td><td>✅🐌</td>
<td>26.9s</td>
<td>28.5s</td><td>✅🐌</td>
</tr>
<tr>
<td>with node_modules</td>
<td>8.6s</td>
<td>9.4s</td><td>✅🐌</td>
<td>7.7s</td>
<td>7.8s</td><td>✅🐌</td>
<td>8s</td>
<td>8.8s</td><td>✅🐌</td>
<td>6.9s</td>
<td>7.4s</td><td>✅🐌</td>
<td>8.3s</td>
<td>9s</td><td>✅🐌</td>
</tr>
<tr>
<td>with lockfile</td>
<td>27.3s</td>
<td>28.6s</td><td>✅🐌</td>
<td>31.5s</td>
<td>31.1s</td><td>✅</td>
<td>28.9s</td>
<td>27.3s</td><td>✅</td>
<td>19.3s</td>
<td>21.5s</td><td>🛑</td>
<td>24.3s</td>
<td>26.5s</td><td>✅🐌</td>
</tr>
<tr>
<td>with warm cache and node_modules</td>
<td>9s</td>
<td>9.2s</td><td>✅🐌</td>
<td>8.4s</td>
<td>8.9s</td><td>✅🐌</td>
<td>8s</td>
<td>8.3s</td><td>✅🐌</td>
<td>7.1s</td>
<td>7.5s</td><td>✅🐌</td>
<td>8.4s</td>
<td>9s</td><td>✅🐌</td>
</tr>
<tr>
<td>with warm cache and lockfile</td>
<td>22.8s</td>
<td>24.4s</td><td>✅🐌</td>
<td>24.8s</td>
<td>27.1s</td><td>✅🐌</td>
<td>23.2s</td>
<td>23.8s</td><td>✅🐌</td>
<td>15.5s</td>
<td>16.2s</td><td>✅🐌</td>
<td>20.4s</td>
<td>21.4s</td><td>✅🐌</td>
</tr>
<tr>
<td>with node_modules and lockfile</td>
<td>9.3s</td>
<td>9.8s</td><td>✅🐌</td>
<td>8.6s</td>
<td>8.9s</td><td>✅🐌</td>
<td>8.6s</td>
<td>10s</td><td>🛑</td>
<td>7.3s</td>
<td>7.5s</td><td>✅🐌</td>
<td>9.2s</td>
<td>9.4s</td><td>✅🐌</td>
</tr>
    </tbody>
  </table>

**Comment by XhmikosR** [comment]
@ruyadorno I'm mostly on Windows, so I might be able to pinpoint the Windows failures. I'll experiment on my fork, because ideally everything should be tested in one place.

**Comment by ruyadorno** [comment]
@XhmikosR thanks! that's really appreciated 😊 (I assume you're talking about https://github.com/npm/cli/pull/666/commits/e0a7a2ffdd77909c198f7f91e9f4b60bc1ed77e0)

It was not that big of a problem for this release since we still had the travis build around anyways but it would be definitely nice to track down what is happening and fix it.

I can share some of the findings from our team so that you can get a head start, for now the problems only occur in the GitHub actions environment (we couldn't reproduce it on our local windows environments) and are related to `npm run` executing node scripts (from within the tests) that contains hash bangs, usually they should be ignored on windows, so it might be something in that specific environment that we're not accounting for in https://github.com/npm/cmd-shim 🤔

**Comment by XhmikosR** [comment]
@ruyadorno : thanks for the info :)

That being said it seems CI is passing fine on my fork on Windows https://github.com/XhmikosR/cli-1/runs/383031136

Maybe you should try re-enabling it? BTW you can force the shell to be something other than the default which is powershell. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#using-a-specific-shell

**Pull request merged**
