### PR TITLE
Port Chores to v8

### PR DESCRIPTION
**Pull request by lukekarrys**
- chore: update scripts
- chore: @npmcli/template-oss@4.7.1
- chore: port docs rewrite to v8
- chore: update snapshot tests for new docs

### CODE REVIEW

**Review by wraithgar — APPROVED** [review]

**Comment by lukekarrys** [comment]
Converting to a draft because #5739 should go first with the necessary changes backported this PR to land in `release/v8`.

**Comment by lukekarrys** [comment]
Marked this as ready since I ported the rest of the relevant changes from #5739

**Comment by lukekarrys** [comment]
I'm fixing the `DEPENDENCIES.md` conflict and then this PR will be ready.

Also note that this should rebased to merge.

**Comment by lukekarrys** [comment]
The conflicts have been fixed and this is ready for review.

**Pull request merged**
