### PR TITLE
Npm audit fixes

### PR DESCRIPTION
**Pull request by XhmikosR**
# What / Why

When doing `npm i` in the master branch, there are 32 vulnerabilities.

## References

I ran `npm audit fix` and manually updated `marked@0.7.0` and `marked-man@0.7.0`:

```
xmr@DESKTOP-2989SN9:~/repos/cli-1$ npm audit

                       === npm audit security report ===

found 0 vulnerabilities
 in 13375 scanned packages
```

I checked a few man pages and everything seems to be fine. Let me know if I broke something :)

PS. I didn't update to `marked@0.8.0` because marked-man depends on marked ^0.7.0.

### CODE REVIEW

**Comment by mikemimik** [comment]
Hey @XhmikosR thanks for the contribution.

The way that we update the vendored deps in the cli is to use a script in the `scripts/` folder

```shell
./scripts/dep-update {name} {version}
```

This script will then update the vendored dep and create the commit for you. You need only run that command on your branch and then run `git push`. If you could rollback the two commits you did, and do them with the script, this pull-request will be in the correct shape!

Let us know if you have any issues with it; we're here to help!


#### npm reference
For npm'ers reference the changelog diff of the deps being updated are below
- [`marked@0.7.0`](https://github.com/markedjs/marked/compare/v0.6.3...v0.7.0)
- [`marked-man@0.7.0`](https://github.com/kapouer/marked-man/compare/0.6.0...0.7.0)

**Comment by XhmikosR** [comment]
That's how I did them.

EDIT: Oh, wait, I also ran npm audit. I don't think just updating the 2 deps fixes all audit issues. In that case I will make a 3rd patch.

**Comment by XhmikosR** [comment]
Oh, wait, I also ran npm audit. I don't think just updating the 2 deps fixes all audit issues. In that case I will make a 3rd patch.

**Comment by XhmikosR** [comment]
Alright, I split the npm audit fixes too.

**Comment by XhmikosR** [comment]
Alright, I split the npm audit patches.

BTW there's a bug somewhere in npm that produces a different lockfile when doing `npm update js-yaml --depth 4` and then `npm i`.

See https://github.com/npm/cli/commit/116bf894376948acd593f4aee1037ab4424977f7 vs https://github.com/npm/cli/commit/b1cf88c24786369ca3c398ae71ba7d94885ad2db

**Comment by XhmikosR** [comment]
Closing this since it's already obsolete AFAICT

**Pull request closed without merging**
