### PR TITLE
 fix(arborist): fix unescaped periods

### PR DESCRIPTION
**Pull request by XhmikosR**
## References

Spotted on https://lgtm.com/projects/g/npm/cli/alerts/?mode=list. If you are not using CodeQL already, I suggest that you set it up :)

### CODE REVIEW

**Comment by ljharb** [comment]
Not sure why codeql would be needed; this is an eslint core rule (that should certainly be enabled)

**Comment by XhmikosR** [comment]
Whatever does the job, ofc. It's just that CodeQL has checks for things ESLint doesn't.

**Comment by wraithgar** [comment]
We are setting codeql up on our repos, we have not done it for the cli yet but it's on the roadmap.

**Comment by lukekarrys** [comment]
> Not sure why codeql would be needed; this is an eslint core rule (that should certainly be enabled)

@ljharb what's the eslint rule for this?

**Comment by ljharb** [comment]
@lukekarrys ah, looking into it, this specific case isn't covered; i usually have all of https://eslint.org/docs/rules/no-control-regex, https://eslint.org/docs/rules/no-div-regex, https://eslint.org/docs/rules/no-regex-spaces, https://eslint.org/docs/rules/no-invalid-regexp, and https://eslint.org/docs/rules/prefer-regex-literals enabled tho.

**Review by lukekarrys — APPROVED** [review]

**Pull request merged**
