### PR TITLE
Fix duplicated hook names

### PR DESCRIPTION
**Pull request by ghost**
I didn't have access to my git history. I had to open another PR. This is for issue #4201

### CODE REVIEW

**Comment by ghost** [comment]
Based on the input from the issue I think this should fix the prefix problem here But, Cli is not passing. 
I appreciate feedback on this.

**Comment by wraithgar** [comment]
The tests in `./test/lib/commands/hook.js` will need to be updated to reflect this new behavior.

Also I believe that whole if statement can be removed.  Appending an empty string to a variable is an unneeded step.

**Comment by ghost** [comment]
Thank you for the review. @wraithgar is it possible to link the parts in the test that need a change?

**Comment by ghost** [comment]
I close this PR. 
Might take some time for me to edit it.

**Pull request closed without merging**
