### PR TITLE
Use the npm lint script on CI.

### PR DESCRIPTION
**Pull request by XhmikosR**
This should be more consistent since it should use the specified standard version and not the latest one.

### CODE REVIEW

**Comment by isaacs** [comment]
> This should be more consistent since it should use the specified standard version and not the latest one.

Note: `npx` will use the version installed in `node_modules` if it exists.  It only pulls the latest if there isn't something else specified locally.  But abstracting it out in case we change our linter at some point in the future is not a bad idea anyway, so at least it's only defined in one place.

**Comment by XhmikosR** [comment]
Oh, cool, I wasn't aware of that. But yeah, this does feel better to me, more consistent.

**Review by mikemimik — APPROVED** [review]
LGTM

**Comment by mikemimik** [comment]
nit: We might want to address the failing tests

**Comment by XhmikosR** [comment]
Might be worth bumping standard to the version that supports the Node.js versions you guys support so that everything is aligned.

**Pull request closed without merging**
