### PR TITLE
@npmcli/run-script@1.8.3

### PR DESCRIPTION
**Pull request by ljharb**
Extracted out of #2654.

### CODE REVIEW

**Comment by wraithgar** [comment]
This is already queued up for `v7.5.4` https://github.com/npm/cli/commit/9a6e9d38abccec793b6ac14871c2b639d62a6c41

**Comment by ljharb** [comment]
@wraithgar yes but it's not on `latest`, and thus #2654 won't pass without it landing here.

To be clear, this is a PR to `latest`, and so it does not matter what's in "a branch that's not `latest`"

**Comment by wraithgar** [comment]
I'm going to make sure the tests pass in the release branch itself so we can get around this hiccup.

**Comment by ljharb** [comment]
I'm just really confused why something would be in the release branch that isn't in the default branch.

**Pull request closed without merging**
