### PR TITLE
Support listing out npm cache

### PR DESCRIPTION
**Pull request by jacobtolar**
The [documentation for npm-cache](https://docs.npmjs.com/cli/npm-cache) says it can list the contents of the cache folder:

> Used to add, list, or clean the npm cache folder.

The `list` functionality isn't actually present, but is supported by [`cacache`](https://www.npmjs.com/package/cacache#ls).

This PR adds a `list` (or `ls`) subcommand to `npm cache` that outputs the contents of the cache in the following format:

```
$ npm cache list
...
make-fetch-happen:request-cache:https://registry.npmjs.org/babel-plugin-transform-es2015-arrow-functions/-/babel-plugin-transform-es2015-arrow-functions-6.22.0.tgz
  url = https://registry.npmjs.org/babel-plugin-transform-es2015-arrow-functions/-/babel-plugin-transform-es2015-arrow-functions-6.22.0.tgz
  path = /Users/jtolar/.npm/_cacache/content-v2/sha1/45/26/92cb711d5f79dc7f85e440ce41b9f244d221
  size = 1752
  time = 1556301242419
make-fetch-happen:request-cache:https://registry.npmjs.org/ultron
  url = https://registry.npmjs.org/ultron
  path = /Users/jtolar/.npm/_cacache/content-v2/sha512/bb/79/1e224496f3bcf5cc6d503ca512a9ff44625ee82e436a7fb24dfde1591a56068846ef7ed2c6fe3f7f233afd74c2d672a4c18e711595d1b2fe64c81f54e9d0
  size = 2101
  time = 1556301242411
...
```

If a different output format would be preferable, I'm happy to change this PR.

### CODE REVIEW

**Comment by isaacs** [comment]
This is a good idea.  But it should use the `cache.ls.stream` interface instead, or else it loads the entire cache into memory.  Otherwise, a fantastic patch.

**Comment by isaacs** [comment]
Also, it should have a `--json` version.

(If you don't get to this, I will eventually, no sweat, not a blocker.)

**Comment by jacobtolar** [comment]
thanks for looking; updated to use `ls.stream` and added a `--json` option.

I don't write much nodejs code, so happy to refactor a bit if you have suggestions for improvements.

**Review by lehtu — APPROVED** [review]

**Comment by darcyclarke** [comment]
@jacobtolar can you add some test coverage? We'd love to land this in our next minor `6.x` release if you can get to it in the next week or so.

**Comment by mikemimik** [comment]
Hey @jacobtolar just a heads up that we'll be releasing a `6.14.0` next week (Dec 3rd, 2019). If you'd like this change to land, could you add some test coverage for it? :D

**Comment by th0rgall** [comment]
If you need this listing feature in the CLI now, a workaround can be found here: https://github.com/yilmazdurmaz/npm-cache-list

**Comment by darcyclarke** [comment]
@jacobtolar apologize this wasn't able to get pulled into v6. We'd love to see `list` & `remove` added to `cache` for v7 if you're willing to rework this PR or update based on the major refactoring we've done. Unfortunately, we're trying not to land any feature work on v6, so I'm going to close this PR for now, but again, encourage this as a feature to be added to v7.

**Pull request closed without merging**
