### PR TITLE
update: re-enable updating local packages

### PR DESCRIPTION
**Pull request by larsgw**
PR https://github.com/npm/npm/pull/11584 removed the possibility of updating local packages (linked with symlinks) with `npm update`.
Reason was that this functionality didn't work in `v3.6.0`. However, the system behind local dependencies
has since changed, and I can't reproduce the original error anymore.

Reverts 53cdb96634fc329378b4ea4e767ba9987986a76e
See discussion in [https://npm.community/t/1725](https://npm.community/t/1725?u=larsgw)

### CODE REVIEW

**Comment by zkat** [comment]
I'd like an 👀 from @iarna on this one.

**Comment by jmfNodejsUser** [comment]
Hello,
Is this correction now available in 6.4.1 ?

**Comment by iarna** [comment]
@jmfNodejsUser It is not, it's not yet been merged.

**Review by iarna — CHANGES_REQUESTED** [review]
Ok, it took me a bit to wrap my head around what this was doing:

This is fixing a problem where `npm update` won't auto-heal missing links. (The work around is to run `npm i` instead, which will.)

I approve of this idea, but there are two things that need to be addressed before it lands:

1. It needs a test (this would have helped us understand what the patch was hoping to achieve)
2. With this patch and a `file:` type dep, `npm outdated -l` crashes, this'll need to be fixed.

**Comment by jmfNodejsUser** [comment]
Thank you for the reply iarna.
How can I help to test this change? OR will somebody from the leader team test the modification?

Your suggestion to use npm i works and installs/links the first/primary dependency (local node module) in the main project. All sub dependencies of the local node modules are not installed/linked. Except when I delete the package-lock.json first and then run "npm i". In this case, it works and installs all primary and sub dependencies which are all local node modules(i.e. not from the npm registry)

**Comment by jmfNodejsUser** [comment]
The problem with using "npm i" is the same mentioned in
https://npm.community/t/npm-install-for-package-with-local-dependency-fails/754

**Comment by larsgw** [comment]
Sorry for the confusion. I added tests. As for the `npm outdated -l` crash, that should be fixed in https://github.com/npm/cli/pull/124.

**Comment by jmfNodejsUser** [comment]
Hello @zkat , @iarna ,
Has this correction been merged into version 6.7.0 release?
I tried downloading version 6.7.0 and testing it.
The "npm update" still does not work for local node modules. 

@larsgw ,
This problem started after npm version 5.6.0 and exists till now. So I think, that the change in v3.6.0 is probably not the reason for these problems since 5.6.0.
The workaround by using "npm install" still needs a deletion of the package-lock.json.

**Review by zkat — APPROVED** [review]
Looks good! Thanks for fixing things up. This looks like it fulfill's @iarna's requirements, so we're good to go. 👍

**Comment by zkat** [comment]
This has been merged by hand. Thanks again, @larsgw!

**Pull request closed without merging**
