### PR TITLE
fix: set proper workspace repo urls in package.json

### PR DESCRIPTION
**Pull request by ljharb**
v5 was published 2 days ago but still points to the archived repo.

### CODE REVIEW

**Comment by lukekarrys** [comment]
Good catch! It looks like we should fix this for all the workspaces:

```js
// npm pkg get repository -ws --include-workspace-root
{
  "npm": {
    "type": "git",
    "url": "https://github.com/npm/cli"
  },
  "docs": {
    "type": "git",
    "url": "https://github.com/npm/cli"
  },
  "@npmcli/arborist": {
    "type": "git",
    "url": "https://github.com/npm/arborist"
  },
  "libnpmaccess": {
    "type": "git",
    "url": "https://github.com/npm/libnpmaccess.git"
  },
  "libnpmdiff": "https://github.com/npm/libnpmdiff",
  "libnpmexec": "https://github.com/npm/libnpmexec",
  "libnpmfund": "https://github.com/npm/libnpmfund",
  "libnpmhook": "https://github.com/npm/libnpmhook",
  "libnpmorg": {
    "type": "git",
    "url": "https://github.com/npm/libnpmorg.git"
  },
  "libnpmpack": {
    "type": "git",
    "url": "https://github.com/npm/libnpmpack.git"
  },
  "libnpmpublish": {
    "type": "git",
    "url": "https://github.com/npm/cli.git"
  },
  "libnpmsearch": {
    "type": "git",
    "url": "https://github.com/npm/libnpmsearch.git"
  },
  "libnpmteam": {
    "type": "git",
    "url": "https://github.com/npm/libnpmteam.git"
  },
  "libnpmversion": {
    "type": "git",
    "url": "git+https://github.com/npm/libnpmversion"
  }
}
```

**Comment by ljharb** [comment]
If there's a single npm command that could _set_ those, including the proper directory field, I'd be happy to update this PR with that result :-)

**Review by lukekarrys — APPROVED** [review]
This is good for now, and will serve as a test that it doesn't get changed when https://github.com/npm/template-oss/issues/66 gets implemented.

**Comment by ljharb** [comment]
Went ahead and manually updated it.

~Note: you're missing a label for `libnpmfund` :-)~

**Comment by wraithgar** [comment]
Waiting on `https://github.com/npm/cli/pull/4487` before merging this so that release-please can do its thing after we merge this.

**Pull request merged**
