### PR TITLE
feat: discrete npm doctor commands

### PR DESCRIPTION
**Pull request by wraithgar**
Changed output to display as each check finishes instead of all at once at the end.

Check added: `checkBinPath`. Checks that the global bin is in your path.

Added grouping to commands.

### CODE REVIEW

**Comment by wraithgar** [comment]
I can edit this to include docs once we've bikeshed the subcommand names.

**Review by fritzy — COMMENTED** [review]
Looks good so far. We can bikeshed the subcommand name next standup.

**Review by nlf — APPROVED** [review]
unless there are objections, i think this makes sense to me. the groupings are named well enough to be intuitive.

**Comment by wraithgar** [comment]
Please squash this one when merging.

**Pull request merged**
