### PR TITLE
Set init license to MIT

### PR DESCRIPTION
**Pull request by ad-m**
I suggest use MIT as default license instead of ISC. Authors of ISC license no longer recommend to use it.

> In 2015, ISC announced they would release their Kea DHCP Software under the Mozilla Public License 2.0, stating, "There is no longer a good reason for ISC to have its own license, separate from everything else".[13] They also preferred a copyleft license, stating, "If a company uses our software but improves it, we really want those improvements to go back into the master source". Throughout the following years, they re-licensed all ISC-hosted software, including BIND in 2016.[14] and ISC DHCP Server in 2017[15]
> The Publications Office of the European Union advises using the MIT license instead of the ISC License in order to reduce license proliferation.[16] 

https://en.wikipedia.org/wiki/ISC_license#Reception

### CODE REVIEW

**Review by Tizzit-max — APPROVED** [review]
@Thankyoubot

**Comment by Satsuki39** [comment]
hello

**Review by Satsuki39 — APPROVED** [review]
hello.lent please

**Comment by darcyclarke** [comment]
@ad-m appreciate this change & the reasoning behind it but I think the [Node.js Package Maintenance WG](https://github.com/pkgjs/create/issues/9) has actually kicked off a great initiative to come up with some best-practices/defaults in this space. If you'd like to change `npm`s defaults, it would be good to open an issue/RFC over on the [Open RFC repo](https://github.com/npm/rfcs)

Alternatively, folks can use existing config to set their personal preferences: 

```
npm config set init_licence = 'MIT'
```

The `ISC` has served us well over the years & I honestly imagine we'll move to `MIT` as the default at some point but it's good if we can queue up that as a discussion first.

**Pull request closed without merging**
