### PR TITLE
outdated: fix special 'remote' deps

### PR DESCRIPTION
**Pull request by larsgw**
Add a special case for 'remote' deps (tarballs). Before b7b54f2d18e2d8d65ec67c850b21ae9f01c60e7e the package names were just looked up in the registry instead. The errors caused by that were hidden by `npm-pick-manifest` not returning the `ETARGET` error that `outdated` expects.

See https://npm.community/t/6187

### CODE REVIEW

**Comment by et304383** [comment]
What is holding this up?

Are there no CI/CD tests that get run before merging changes to npm?  Trying to understand how something so important as `npm update` was broken with no one noticing.

**Comment by 0xsuid** [comment]
@isaacs any update on this issue??

**Comment by larsgw** [comment]
It seems to be merged indirectly (7f8d52ed51bac0bb985e7772075d7bf86dafc6ad) and will probably be included in the next release.

**Comment by isaacs** [comment]
Yes, It's in the `release-next-6.10.0` branch, and will be in 6.10.0.

**Pull request closed without merging**
