### PR TITLE
feature: configurable audit level

### PR DESCRIPTION
**Pull request by lennym**
This is a port of my old PR at https://github.com/npm/npm/pull/20992

It allows `npm audit` to exit with a zero exit code if only vulnerabilities below a defined threshold are detected. The default is left at `low` so it should be wholly non-breaking.

More discussion at https://npm.community/t/allow-a-configurable-vuln-level-to-make-npm-audit-fail/245/5

### CODE REVIEW

**Review by zkat — COMMENTED** [review]
I'm 👍 on this one, specially since all it does is modify the loglevel for failure. I'd like to get sign-off from @iarna and @npm/security-product to make sure this aligns with their ideas around audit, and the rest looks great. Thanks for writing tests and doing such a nicely-targeted feature! 🎉

**Comment by zkat** [comment]
p.s. feel free to ignore the CI failure. It's unrelated to your PR.

**Comment by evilpacket** [comment]
I'm 👍 on this as it's a desired user feature to only break on certain levels of vulns and brings us closer to feature parity with legacy `nsp`

**Review by zkat — APPROVED** [review]
LGTM, then! Woo!

**Pull request merged**
