### PR TITLE
update bin-links dependency

### PR DESCRIPTION
**Pull request by kieckhafer**
# What / Why
`bin-links v1.1.7` has been failing in `Snyk` security tests in this project as well as others. This PR updates to the latest version of `bin-links`, `v2.0.0`, to address these failures.

image

### CODE REVIEW

**Comment by mikemimik** [comment]
Hey @kieckhafer thanks so much for the contribution!

The way that we update the vendored deps in the cli is to use a script in the `scripts/` folder

```shell
./scripts/dep-update {name} {version}
```

This script will then update the vendored dep and create the commit for you. This commit should included an updated `node_modules/` folder. The easiest way to accomplish this is to rollback your commit with `git reset HEAD^`, then run the script from above. Doing that and then pushing to your branch will get this pull-request into the correct shape!

Let us know if you have any issues with it; we're here to help!

**Comment by kieckhafer** [comment]
Thanks @mikemimik, I think I updated as you described.

**Comment by isaacs** [comment]
bin-links 2 is a breaking change and not compatible with npm v6.  What's the security issue?  It'll have to be fixed in a v1 release, if it isn't already addressed.

**Comment by isaacs** [comment]
I ask because 1.1.7 and 1.1.6 were both security related updates.  There were no relevant changes between 1.1.7 and 2.0.0, except for dropping bluebird, and dropping support for EOL node versions.

**Comment by kieckhafer** [comment]
@isaacs I actually am not sure what the issue is, `snyk` was throwing it 10 days ago when I first created this, but rechecking now it seems to be gone so perhaps it was just a temporary error in `snyk`. I will close this and re-open something if I see it pop up again.

**Pull request closed without merging**
