### PR TITLE
refactor: replace lodash.without with Array#filter

### PR DESCRIPTION
**Pull request by SukkaW**
The PR removes `lodash.without` dependency by replacing `lodash.without` with native JavaScript `Array#filter`.

### CODE REVIEW

**Comment by SukkaW** [comment]
test this please ✅

**Comment by isaacs** [comment]
We're not able to land this in v6, because it's a breaking change, given the Node.js versions that v6 supports.  But, if you'd like to send PRs against the `release/v7.0.0-beta` branch that replace lodash deps with native JavaScript, that'd be much appreciated!

**Comment by ljharb** [comment]
@isaacs which node versions that npm v6 supports lacks Array filter, which was part of ES5 and in node 0.10? (or arrow functions, which landed in node 4?)

**Comment by SukkaW** [comment]
@ljharb Since `npm@7` is at the corner, keep `npm@6` stable will be fine.

**Pull request closed without merging**
