### PR TITLE
fix(docs): add missing note

### PR DESCRIPTION
**Pull request by behnammodi**
Added missing note

### CODE REVIEW

**Review by Chutancdn — APPROVED** [review]

**Comment by wraithgar** [comment]
Can this be reworded a little? It's not clear what is being communicated by the addition?  Perhaps something like "commands will be run in each workspace in the order they appear in your package.json"?

**Comment by behnammodi** [comment]
@wraithgar Sure

**Review by lukekarrys — CHANGES_REQUESTED** [review]
I agree with @wraithgar's comment that this should be reworded a little.

**Comment by behnammodi** [comment]
@wraithgar @lukekarrys Done

**Review by wraithgar — APPROVED** [review]

**Review by lukekarrys — APPROVED** [review]

**Comment by wraithgar** [comment]
@behnammodi can you resolve the conflicts this has against `release-next`? I know the default branch in npm is `latest` but the `release-next` branch is the one you want to branch off of for PRs.

**Comment by wraithgar** [comment]
Sorry about that, this file usually doesn't get a lot of activity but it just so happened to get conflicting updates in the last two weeks.

**Comment by behnammodi** [comment]
@wraithgar no problem, sure, I'll do it

**Comment by behnammodi** [comment]
@wraithgar Done

**Review by Bugger1980 — COMMENTED** [review]
[logs_935.zip](https://github.com/npm/cli/files/10372634/logs_935.zip)

**Comment by Bugger1980** [comment]
[=0&at=2ahUKEwjp.txt](https://github.com/npm/cli/files/10372645/0.at.2ahUKEwjp.txt)
> [logs_935.zip](https://github.com/npm/cli/files/10372634/logs_935.zip)

**Pull request merged**
