### PR TITLE
Automatically audit dependency licenses

### PR DESCRIPTION
**Pull request by kemitchell**
This PR adds an npm script and Travis CI script line to check dependencies' licenses against a configured acceptable-license rule.  I've also added dependencies that lack proper license metadata to a whitelist, after checking their terms by hand.

Please note that I've only whitelisted _the current versions_ of dependencies without valid license metadata.  If we bump those deps, and the new versions don't have valid metadata, either, the license check will fail until the new versions are added to the whitelist.  There are only four of those deps at present.

cc @iarna

### CODE REVIEW

**Review by annunah — APPROVED** [review]

**Comment by kemitchell** [comment]
Here's the Travis CI log where the output starts:

https://travis-ci.com/npm/cli/jobs/145843764#L1245

**Comment by kemitchell** [comment]
I believe this is ready to go.

**Comment by PixleProgrambetaxl** [comment]
+1

**Comment by annunah** [comment]
Lets try:)

**Review by zkat — APPROVED** [review]
I mean if our lawyer thinks this is a good idea, then I think this is a good idea. Let's roll with it and see.

**Comment by kemitchell** [comment]
This is basically like having bumpers at a bowling alley. I trust y'all are checking licenses of deps as you bring them in, but this will help catch anything that slips past.

**Pull request merged**
