### PR TITLE
Update node.js

### PR DESCRIPTION
**Pull request by zhennann**
Provide more error details for semver compare

### CODE REVIEW

**Comment by wraithgar** [comment]
What error is this trying to catch?

**Comment by zhennann** [comment]
In the `package.json` file, if `version` is empty string, the code `semver.gte(other.version, this.version)` will throw a TypeError with `Invalid version:`. However, we don't know which npm pkg caused this error. So, we should catch the error and provide more details.

**Comment by wraithgar** [comment]
If you have a node in your tree with no version that's a much bigger issue than this one error and should probably be handled elsewhere.  How is a node with no version getting into the tree?

**Comment by zhennann** [comment]
Just as what I've encountered, in a specific scenario, package-lock.json log a npm pkg, which not exists on the disk. 
Front end engineering always mixes multiple tools,  leading to conflicts in certain execution actions.

**Comment by wraithgar** [comment]
Not existing on disk is vastly different than not having a version attribute.  This is one of the reasons it's important to be very specific about the use case this is trying to address.  Another reason is it informs what the test looks like.

**Pull request closed without merging**
