### PR TITLE
gar/libnpmexec fixes

### PR DESCRIPTION
**Pull request by wraithgar**
- deps: add @npmcli/fs@2.1.1
- deps: add semver@7.3.7
- deps: @npmcli/run-script@4.2.0
- fix: properly find locally/globally/npxCache packages
- fix: use binPaths

### CODE REVIEW

**Comment by wraithgar** [comment]
Closes https://github.com/npm/cli/issues/3210

**Comment by wraithgar** [comment]
Closes https://github.com/npm/cli/issues/5132
Closes https://github.com/npm/cli/issues/5018

**Comment by wraithgar** [comment]
Closes https://github.com/npm/cli/issues/4204

**Comment by wraithgar** [comment]
Closes https://github.com/npm/cli/issues/3058

**Review by nlf — APPROVED** [review]

**Comment by jlarmstrongiv** [comment]
@wraithgar comment converted to https://github.com/npm/cli/issues/5269

**Pull request merged**
