### PR TITLE
fix(resolve): use nodejs implementation of url parse instead of WHATWG URL in case of support git+ssh protocol

### LINKED ISSUE #5278: [BUG] git+ssh does not work with version 8.16
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Hello

Using the latest version of npm `8.16` and latest `14.20` version of node.js.

I have few dependencies which i install from local git server. \
When i remove `node_modules` folder and want to install packages again with command `npm i` i get error:

```
2833 verbose stack TypeError [ERR_INVALID_URL]: Invalid URL: git+ssh://git@***:frontend/utils.git#6d45447e0c5eb6cd2e3edf05a8c5a9bb81950c79
2833 verbose stack     at new NodeError (internal/errors.js:322:7)
2833 verbose stack     at onParseError (internal/url.js:270:9)
2833 verbose stack     at new URL (internal/url.js:346:5)
2833 verbose stack     at Arborist.[registryResolved] (***/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:721:25)
2833 verbose stack     at Arborist.[extractOrLink] (***/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:641:72)
2833 verbose stack     at ***/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:607:35
```

But with npm `8.15.1` is works fine.

### Expected Behavior

Packages with git+ssh path should be installed

### Environment

- npm: 8.16.0
- Node.js: v14.20.0
- OS Name: MacOS 11.6.8
- System Model Name: Macbook Pro

### PR DESCRIPTION
**Pull request by delagen**
Use nodejs implementation of url parse instead of WHATWG URL in case of support git+ssh protocol

## References
Closes #5278

### CODE REVIEW

**Review by frank-dspeed — COMMENTED** [review]
LGTM++++

**Comment by fritzy** [comment]
@Delagen can you add a test to show this working with currently unsupported URL types?

**Comment by delagen** [comment]
@fritzy I think I will spend too much time trying understand how tests work in this project

I found details it not work only with non github url
For example: private Gitlab


#works
npm i git+ssh://git@github.com:chalk/chalk.git#v5.0.1

#fail
npm i git+ssh://git@git.own.com:group/repo.git#branch

npm ERR! code ERR_INVALID_URL
npm ERR! Invalid URL


Seems it does not support colon inside
npm i git+ssh://git@git.own.com/group/repo.git#branch
Works

**Comment by frank-dspeed** [comment]
@Delagen good point the npm project is since long time not in shape anymore i also did no pull requests for all the issues any more as i do not aggree with the overall project handling my suggestion is download .patch files from github and let this issue open then write that you need help with the pull request and some one who is familar with the project will jump in.

i created for my self a new npm package under my @scrope and there i put simply inside the package.json the git patches after install that is a good method to not be blocked by the npm project management it self. hope it helps you

**Comment by lukekarrys** [comment]
Thanks for the PR to fix this. We didn't want to land something using a deprecated Node API, so I was able to add a method to our package that we use for parsing git host shorthands, so it can also parse urls: https://github.com/npm/hosted-git-info/pull/176

This should land as part of #5758 which will fully close this bug.

**Comment by frank-dspeed** [comment]
in general as this is needed i only want to leave a comment for the next generation. If you find such issues again never do a package for that rule of thumb if your package maintainance code is more then 200% of your own code create a new file in a existing repo most best create a folder that you call /modules/module-name/module-name.js

call it a day.

## About the down voter
He has a other mindset then me you do not need to give that much attention it is his private war for keeping the things like there where in the 1970th he also is fame for the quote: treat ram as infinite in JS

**Pull request closed without merging**
