### PR TITLE
fix: make prune rule work on case-senstive file systems

### PR DESCRIPTION
**Pull request by lpinca**
On case-sensitive file systems the rule fails because `README.markdown`
is removed.

### CODE REVIEW

**Comment by wraithgar** [comment]
Fresh checkout:

```sh
~/D/n/x $ ls -al cli/node_modules/mkdirp
total 56
drwxr-xr-x    9 wraithgar  staff   288 Apr 27 09:32 ./
drwxr-xr-x  233 wraithgar  staff  7456 Apr 27 09:32 ../
-rw-r--r--    1 wraithgar  staff   448 Apr 27 09:32 CHANGELOG.md
-rw-r--r--    1 wraithgar  staff  1166 Apr 27 09:32 LICENSE
-rw-r--r--    1 wraithgar  staff  8507 Apr 27 09:32 README.markdown
drwxr-xr-x    3 wraithgar  staff    96 Apr 27 09:32 bin/
-rw-r--r--    1 wraithgar  staff  1029 Apr 27 09:32 index.js
drwxr-xr-x    8 wraithgar  staff   256 Apr 27 09:32 lib/
-rw-r--r--    1 wraithgar  staff   804 Apr 27 09:32 package.json
~/D/n/x $ cd cli/
~/D/n/x/cli (latest|✔) $ make prune
node bin/npm-cli.js prune --production --no-save --no-audit

changed 14 packages in 993ms
git status is clean
~/D/n/x/cli (latest|✔) $ git status
On branch latest
Your branch is up to date with 'origin/latest'.

nothing to commit, working tree clean
~/D/n/x/cli (latest|✔) $ ls -al node_modules/mkdirp
total 56
drwxr-xr-x    9 wraithgar  staff   288 Apr 27 09:33 ./
drwxr-xr-x  241 wraithgar  staff  7712 Apr 27 09:33 ../
-rw-r--r--    1 wraithgar  staff   448 Oct 26  1985 CHANGELOG.md
-rw-r--r--    1 wraithgar  staff  1166 Oct 26  1985 LICENSE
drwxr-xr-x    3 wraithgar  staff    96 Apr 27 09:33 bin/
-rw-r--r--    1 wraithgar  staff  1029 Oct 26  1985 index.js
drwxr-xr-x    8 wraithgar  staff   256 Apr 27 09:33 lib/
-rw-r--r--    1 wraithgar  staff   804 Oct 26  1985 package.json
-rw-r--r--    1 wraithgar  staff  8507 Oct 26  1985 readme.markdown
```

**Review by wraithgar — APPROVED** [review]
Good catch, thank you

**Comment by nlf** [comment]
is renaming a file that's part of another package within our bundled dependencies really the right fix for this?

**Comment by nlf** [comment]
> is renaming a file that's part of another package within our bundled dependencies really the right fix for this?

answered my own question, apparently it's in lowercase (like this change) for the package as it is published but somehow we've had it named wrong this entire time.. that seems really strange. i wonder how we ended up with it wrong in the first place.

**Comment by wraithgar** [comment]
> answered my own question, apparently it's in lowercase (like this change) for the package as it is published but somehow we've had it named wrong this entire time.. that seems really strange. i wonder how we ended up with it wrong in the first place.

What I think happened is that it was upper case in the repo, cloned into the cli, changed in the repo, and then never encountered again in the cli during the deploy/prune process on a system that cared about filename case, so git never showed that there was a change during that process.

**Comment by lpinca** [comment]
That's what I think happened as well.

**Pull request merged**
