### PR TITLE
fix(docs): fix headline clash during navigation

### PR DESCRIPTION
**Pull request by AnilSeervi**
Remove `Description` headline to facilitate navigation to `description` property headline of `package.json`

### CODE REVIEW

**Comment by wraithgar** [comment]
All of the other markdown files  have that top-level `Description` heading.  Is it possible to force the anchor for the duplicate heading to something else i.e.

```md
### [description](#package-json-description)
```

**Comment by AnilSeervi** [comment]
> 
> 
> All of the other markdown files have that top-level `Description` heading. Is it possible to force the anchor for the duplicate heading to something else i.e.
> 
> ```lisp
> ### [description](#package-json-description)
> ```

No, then the heading would have to be `package json description`

**Comment by wraithgar** [comment]
We're gonna consider this a docs bug, removing the header is not the right solution.

**Comment by wraithgar** [comment]
https://github.com/npm/documentation/issues/34

**Comment by AnilSeervi** [comment]
The Section could be changed to something else like Getting Started.

**Pull request closed without merging**
