### PR TITLE
feat(find-dupes): pretty-print diff on `--dry-run`

### PR DESCRIPTION
**Pull request by chowkapow**
`npm find-dupes` for v7 currently does not have a descriptive message of what packages are being added/changed/removed.
This PR will output how each package would change.

image

## References

Related to #2687

## TODO

- Add test cases
- When package version remains the same, printing `change mkdirp 1.0.4 -> 1.0.4` is not useful. Need to find the actual change.

image

- Determine how to find node module path changes like below. I'm unable to find where this info lies in the `diff` object.
```
$ npx npm@6 find-dupes
move	source-map	0.5.7	node_modules/@babel/core/node_modules/source-map		node_modules/tap/node_modules/@babel/core/node_modules/source-map
move	@babel/helper-annotate-as-pure	7.10.4	node_modules/@babel/helper-annotate-as-pure		node_modules/tap/node_modules/@babel/helper-annotate-as-pure
move	@babel/helper-builder-react-jsx	7.10.4	node_modules/@babel/helper-builder-react-jsx		node_modules/tap/node_modules/@babel/helper-builder-react-jsx
move	@babel/helper-member-expression-to-functions	7.10.5	node_modules/@babel/helper-member-expression-to-functions		node_modules/tap/node_modules/@babel/helper-member-expression-to-functions
... etc
```

### CODE REVIEW

**Review by RonSherfey — CHANGES_REQUESTED** [review]
requested changes .1

**Review by RonSherfey — CHANGES_REQUESTED** [review]
changes 2

**Comment by chowkapow** [comment]
Hey @RonSherfey, what comments did you have for this? I can't find them for some reason.

How can I achieve the styling as suggested in the RFC meeting?
`needs some work on the styling (should be consistent with outdated output with standardized colums/tablet layout)`

**Review by RonSherfey — APPROVED** [review]
changes 2.0

**Pull request closed without merging**
