### PR TITLE
fix(docs): revert auto-generated portion of docs

### PR DESCRIPTION
**Pull request by wraithgar**
The content in this portion of the docs is auto-generated.

## References
Reverts https://github.com/npm/cli/pull/3630

### CODE REVIEW

**Comment by isaacs** [comment]
RSLGTM.  Would be nice to _also_ re-add it to the spot where it belongs, maybe pull in the commit from #3630 and edit it to be in the right place?

**Review by nlf — APPROVED** [review]

**Comment by ljharb** [comment]
Does generated content need to be in the repo at all? Or could it be generated on prepack

**Comment by wraithgar** [comment]
> Does generated content need to be in the repo at all? Or could it be generated on prepack

Ideally yes the generated content will be separate from its source components.  We made an iterative step to swap out the generated content inside already existing files, and eventually will want to take the next step.

**Comment by wraithgar** [comment]
> RSLGTM. Would be nice to _also_ re-add it to the spot where it belongs, maybe pull in the commit from #3630 and edit it to be in the right place?

Yeah I added a comment to the original PR but for now this gets us back to being able to cut the nodejs/node pr

**Pull request merged**
