### PR TITLE
fix: make omit flags work properly with workspaces

### LINKED ISSUE #6441: [BUG] npm ci --omit-dev is not omitting dev dependencies of child workspaces when conflicting with root
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When using workspaces, having a dev dependency which has one version in root and a different conflicting version inside a workspace folder and running `npm ci --omit=dev`it will ignore dev deps present in the root package.json but install dev dependencies for the child workspaces. 

I found an issue relating to it [here](https://github.com/npm/cli/issues/3382) but it was back in version 7 and has been fixed as well apparently. 

### Expected Behavior

Using omit=dev should not install dev deps for root or any child workspace

### Steps To Reproduce

1. Using npm version 9.6.6
2. Create a project with a sub folder which is also a workspace in the root package json. Added some dev dependency to the root package json and some different version of the dev dependency to the package json inside the sub folder so that it conflicts and is not hoisted
3. Run `npm ci --omit=dev` from root or `npm ci --omit=dev` from inside the sub folder or `npm ci --omit=dev --workspace <package-name-in-package-json-in-subfolder>` from either folder
4. The dev dependency inside subfolder will get installed

Repo with minimum reproducible example: https://github.com/Rayyan98/npm-issue

### Environment

- npm: 9.6.6
- Node.js: 18.14.1
- OS Name: Mac OS
- System Model Name: -
- npm config:
```ini
; node bin location = /Users/rayyanulhaq/.nvm/versions/node/v18.14.1/bin/node
; node version = v18.14.1
; npm local prefix = /Users/rayyanulhaq/Work/rewaa/simple
; npm version = 9.6.6
; cwd = /Users/rayyanulhaq/Work/rewaa/simple
; HOME = /Users/rayyanulhaq
; Run `npm config ls -l` to show all defaults.```

### PR DESCRIPTION
**Pull request by Rayyan98**
I am encountering an issue in using work-spaces whereby if i have a dev dependency at the root of my project with some version v1 and the same dependency inside one of the work-spaces which is a sub-folder in the project root with version v2 also as dev dependency that conflicts with v1 and try to do `npm ci --omit=dev` it skips installing the v1 dependency which was at project root but still installs the v2 dependency that was in the child workspace. I would expect that v2 should also not be installed. I have raised an issue for it here https://github.com/npm/cli/issues/6441 which also includes a link to minimum reproducible example.

In reify under arborist I found a filter condition which runs through the idealTree inventory to see which packages needed to be filtered out when omit dev or omit peer options etc are passed. Along with checking which flag is enabled and which packages is which type it also includes a condition of `node.top.isProjectRoot`. I don't fully understand the purpose of the last condition but am guessing, it is there so that the package is only filtered out if it is going to be directly under the root node_modules folder and not if it is going to be under the node_modules of some package which is under the actual root node_modules folder. I have extended the condition so that it is also filtered out if its top is a workspace which i think would translate to, that it should also be filtered out if its directly under the node_modules of a workspace folder.

## References
  Fixes #6441 

PS: It is my first time contributing to open source please excuse me if i have not followed proper procedure or otherwise missed something,

### CODE REVIEW

**Comment by Rayyan98** [comment]
Adding screen shot for better clarification.

On running `npm i --omit=dev`, the `package1/node_modules/dotenv` dev dependency is installed anyway

image

**Comment by Rayyan98** [comment]
Changed commit message to make it inline with lint rules

**Comment by Rayyan98** [comment]
Updated PR Title to comply with lint rules

**Comment by Rayyan98** [comment]
Updated PR Title to comply with lint rules (2)

**Comment by wraithgar** [comment]
Is there a test that we can have to show this behavior working as intended?

**Comment by wraithgar** [comment]
Don't worry too much about linting the commit, we purposely made our CI look at the PR *or* the commit(s) so that we could change it in the PR before landing it.  It's not something we are asking contributors to fret about.

**Comment by Rayyan98** [comment]
Added a test case

**Comment by Rayyan98** [comment]
@wraithgar Do we have some ETA for this, we are waiting to shift our monorepo to workspaces

**Comment by lukekarrys** [comment]
@Rayyan98 Thank you for your patience with this. One thing I was wondering is how we would want this to behave is using `--omit=dev` in conjunction with the `--workspace`, `--workspaces`, or `--include-workspace-root` flags.

I pushed a commit to this PR where it will filter the omit list based on those flags. Your originally test case still passed, and I added a few more. Would you be able to confirm if shifting your monorepo to workspaces still works as expected with this additional change?

**Comment by Rayyan98** [comment]
Yes if the original test case is passing then it should work fine

**Review by lukekarrys — APPROVED** [review]

**Comment by lukekarrys** [comment]
@wraithgar This should be squashed and merged

**Comment by wraithgar** [comment]
Thank you @Rayyan98

**Comment by spearmootz** [comment]
i think this still happens
if i install @feathersjs/configuration i end up with something like this

├─┬ @feathersjs/configuration@5.0.25
│ └─┬ @feathersjs/schema@5.0.25
│   └── typescript@5.4.5 deduped

but they are all dev-dependencies and yet when i install with --omit dev or --omit=dev i always get typscript installed again

**Pull request merged**
