### PR TITLE
install: match git semver ranges

### PR DESCRIPTION
**Pull request by larsgw**
Let equivalent git semver ranges match. I'm not really sure how to integration-test this without actually cloning git projects at the moment.

See https://npm.community/t/3784.

### CODE REVIEW

**Review by zkat — APPROVED** [review]
This looks good! I think I have some hesitation about using the `version` field for git stuff, when resolution happens off tag labels but... I think it's safe to say we consistently assume that package.json's `version` field is going to match git tags when using git dependencies, so I think this'll be fine, and I don't see a better way to do this. Thank you!

**Review by iarna — CHANGES_REQUESTED** [review]
This isn't quite safe:

If the existing child on disk is from the registry, this will result in changing that to be a git-based range not result in updating the child (when it should, as different sources are not the same).

I would suggest that we add an additional restriction to this check:

The child requested should be from the same git repo as the source requested. So the overall logic would be:

"Is this child installed from the same git repo and is its version in our range?"

**Comment by iarna** [comment]
This also definitely needs a test (not testing this area of code has burned us many times in the past), but I believe can be tested without having to setup a local git server, by injecting a mock of `lib/fetch-package-metadata` (we use `require-inject` for this).

(As an aside, we do actually do some full git functional tests, where we create a local git repo and fire up a server and talk to that. But as I say, I'm hopeful that can be avoided here.)

**Comment by larsgw** [comment]
Thanks for the feedback! While I'm not entirely familiar with all of the possibilities in that function, this is definitely something I should have caught. I don't really know if I can find much time to work on this and the tests this week, but I'll see (and otherwise, there's next week).

**Comment by larsgw** [comment]
I added code that should fix the issue you mentioned, and tests. There *are* some problems with the tests:

  * I don't think I can mock part of npm while using `common-tap.js`
  * Using npm directly works, but I don't think I can completely silence output, like `install`s "added n new packages"
  * Changing the test to make sure repository sources are the same failed due to outright removing a dependency. This also happens without any of the changes I applied, and seems to be related to some lack of metadata in the manifest, but I couldn't pinpoint the part were it's removed.

**Comment by zkat** [comment]
>     * I don't think I can mock part of npm while using `common-tap.js`

This is correct.

>     * Using npm directly works, but I don't think I can completely silence output, like `install`s "added n new packages"

You can! You need to add `"--loglevel", "silent"` to the arguments. :)

>     * Changing the test to make sure repository sources are the same failed due to outright removing a dependency. This also happens without any of the changes I applied, and seems to be related to some lack of metadata in the manifest, but I couldn't pinpoint the part were it's removed.

I'm confused about this bit. Can you be more specific?

**Comment by larsgw** [comment]
> You can! You need to add `"--loglevel", "silent"` to the arguments. :)

IIRC, not on [stdout](https://npm.community/t/npm-rebuild-silent-is-not-silent/3834?u=larsgw).

> I'm confused about this bit. Can you be more specific?

Yeah I had a hard time understanding it myself now. Basically the test where the installed version is the same version as the requested one, but from a different repository failed, but it also failed without any of my changes so that's probably due to my mocks. I'll look at it later.

**Comment by iarna** [comment]
If you're mocking things in npm and want silence (or to capture output), inject a mock for `lib/utils/output.js`

**Review by zkat — APPROVED** [review]
Looks good to me! Thanks for writing up tests. :tada: 🍌

**Comment by larsgw** [comment]
I added a mock for `utils/output.js`. It seems to work but I broke the tests on my end (a290a67dcdb49247eeb1c428ec8fedbd8d3120c5) so that it works with the current `release-next`, so I cannot know for sure until CI is done.

**Pull request merged**
