### PR TITLE
chore(refactor): promisify completion scripts

### PR DESCRIPTION
**Pull request by wraithgar**
We also removed the "none" script because we handle a missing
script just fine. There is no need to put an empty one in

### CODE REVIEW

**Comment by wraithgar** [comment]
Looks like something in the last patch to npm brought in more fs.promises references. That'll have to be fixed before CI is green.

**Review by nlf — CHANGES_REQUESTED** [review]
this is an excellent refactor to remove some weirdness

that said, we should pick one way to define the completion function and stick with it. we have currently

`function (opts) {}`
`async function (opts) {}`
`opts => {}`
`(opts) => {}`
`async (opts) => {}`

i think the last one makes the most sense to use as the canonical definition style since we use arrow functions for most things, and just always declaring it async is nice for consistency

**Comment by wraithgar** [comment]
@nlf very good point. I tried to be aware of that when I was changing the tap functions (I think I got them to all be `async t =>`, but obviously forgot to do that to the actual function I was refactoring.  I'll change that.

**Review by nlf — APPROVED** [review]
:tada:

**Pull request closed without merging**
