### PR TITLE
Fix package id in shrinkwrap lifecycle step output

### LINKED ISSUE #20756: undefined preshrinkwrap, shrinkwrap and postshrinkwrap
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?
create `package.json` containing this:
``` json
{
  "name": "test.app.name",
  "scripts": {
    "preshrinkwrap": "echo \"preshrinkwrap\"",
    "shrinkwrap": "echo \"shrinkwrap\"",
    "postshrinkwrap": "echo \"postshrinkwrap\"",
    "preinstall": "echo \"preinstall\"",
    "install": "echo \"install\"",
    "postinstall": "echo \"postinstall\""
  }
}
```
run `npm i`, and you will see this output:
```

> test.app.name@ preinstall /Users/safareli/dev/foam/tmp-scr
> echo "preinstall"

preinstall

> test.app.name@ install /Users/safareli/dev/foam/tmp-scr
> echo "install"

install

> test.app.name@ postinstall /Users/safareli/dev/foam/tmp-scr
> echo "postinstall"

postinstall

> undefined preshrinkwrap /Users/safareli/dev/foam/tmp-scr
> echo "preshrinkwrap"

preshrinkwrap

> undefined shrinkwrap /Users/safareli/dev/foam/tmp-scr
> echo "shrinkwrap"

shrinkwrap

> undefined postshrinkwrap /Users/safareli/dev/foam/tmp-scr
> echo "postshrinkwrap"

postshrinkwrap
npm WARN test.app.name@ No description
npm WARN test.app.name@ No repository field.
npm WARN test.app.name@ No license field.
```
for install scripts you see an app name but not for shrinkwrap scripts instead you get undefined

### supporting information:

 - `npm -v` prints: 5.4.2
 - `node -v` prints: v6.11.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS

### PR DESCRIPTION
**Pull request by bz2**
Currently all logging related to shrinkwrap steps reports 'undefined'
for the package in output and log messages.

This is due to the package associated with the `idealTree` being
recreated in the `savePackageJson()` method which precedes these
steps. For now, just copy forward the `_id` attribute which lifecycle
logging expects, but note that mutating `package` here is surprising.

Fixes npm/npm#20756

### CODE REVIEW

**Comment by bz2** [comment]
@ruyadorno @claudiahdz Is there anything I can do to help get this reviewed and landed?

What kind of discussion is needed exactly? This is a pretty simple change that improves error output for steps after post install.

**Comment by isaacs** [comment]
This looks good to me.  It's irrelevant in npm v7, but we may as well fix this little thing in the meantime.

Sorry for the delay, we're all pretty focused on getting the next major done.  Thanks for your patience.

**Review by isaacs — APPROVED** [review]

**Comment by bz2** [comment]
@claudiahdz It it possible for you to merge this? I do not have write access to actually land.

@isaacs Thank you for the review. I like the streamlined upcoming changes, though it now doesn't say which script has failed:
```
$ node ~/branches/npm-cli/lib/npm.js i --save-exact
npm ERR! code 1
npm ERR! path /tmp/pkg/node_modules/fail
npm ERR! command failed
npm ERR! command sh -c false
```

**Comment by claudiahdz** [comment]
This will be added on `6.14.7`.

**Pull request closed without merging**
