### PR TITLE
install: fix install checks for optional/dev dependencies

### PR DESCRIPTION
**Pull request by larsgw**
Problem: when a sub-dependency is required by an optional dependency in two different ways (e.g. once directly and once via another sub-dependency) the sub-dependency checking process ends up at the (optional) parent dependency twice, always failing the check.

Fix: make sure that the tracking of already seen packages has no effects on parallel paths.

See https://npm.community/t/2569

### CODE REVIEW

**Review by lucasfeliciano — APPROVED** [review]

**Comment by zkat** [comment]
I'd like to get a review from @iarna on this one.

**Comment by surmacz** [comment]
In which version this this fix is going to be released?

**Comment by mramato** [comment]
I'm not one for "me-too" posts, but I was extremely disappointed to see this didn't go into npm 6.5.0.  It's preventing me and my team from making effective use of package-lock.json or submitting it to our source control.

Is there anything the community can do to help move this patch along?  As an OSS maintainer, I completely understand that things can sometimes fall through the cracks when it comes to waiting for someone to review them, but this seems like a fairly minimal, high-impact change to the source.

**Comment by iarna** [comment]
This was merged as https://github.com/npm/cli/commit/134207174652e1eb6d7b0f44fd9858a0b6a0cd6c and will be in the next release of npm (which will be the first or second week of January, schedules depending).

I rewrote the test to be a bit more in our current style and take advantage of our test tooling. You can see the changes here:

https://gist.github.com/iarna/ca94b7b044cd55c95753964aad27e4d2

**Comment by rooby** [comment]
None of the recent release notes seem to have a link to this pull request.  Did it make it into 6.6.0 or 6.7.0?

Was it this one in 6.6?

> 134207174 npm.community#2569 Fix checking for optional dependencies. (@larsgw)

**Comment by andersk** [comment]
@rooby Yes, see the previous comment.

**Comment by khitrenovich** [comment]
Is there any chance that npm v6.6 will be bundled with the next Node v10.x release? Say, v10.16...

**Comment by larsgw** [comment]
@khitrenovich it's being worked on: https://github.com/nodejs/node/pull/25804

**Pull request closed without merging**
