### PR TITLE
chore: add smoke-test that will use current npm source to overwrite itself

### PR DESCRIPTION
**Pull request by lukekarrys**

### CODE REVIEW

**Comment by lukekarrys** [comment]
I also ran the smoke publish tests manually to make sure the new smoke test passes there as well: https://github.com/npm/cli/actions/runs/5054056601

**Comment by lukekarrys** [comment]
Ignore the 20 something force pushes. If checks are green, this is ready for review.

**Review by wraithgar — APPROVED** [review]
Having a test that works in Windows is kind of a big deal. In the past it was Windows that manifested this error of npm not being able to update over the top of itself.

**Comment by lukekarrys** [comment]
All the smoke tests, including this new one, run in Windows. It's only the smoke publish test that doesn't run in Windows due to the git dirty check failing at various points during the test.

That test has never run in Windows, but is mainly to test our publish script and then ensure that the existing smoke tests still pass after a mock publish.

This new test is asserting that:
- the source controlled version of npm can pack and install itself globally
- then that global version is able to pack and install an empty tarball without failing

**Pull request merged**
