### PR TITLE
Fix issue with sub folder local references

### PR DESCRIPTION
**Pull request by jtwebman**
This is using @iarna PR https://github.com/npm/cli/pull/40 adding tests and rebasing on latest.

fixes: https://npm.community/t/issue-npm-install-with-local-packages-and-symlinks-enoent/518

- [x] Repro test from https://npm.community/t/npm-install-for-package-with-local-dependency-fails/754/10

### CODE REVIEW

**Comment by jtwebman** [comment]
@zkat or any one else that has write access to this repo can you re-run the failed test? Looks like Travis-CI had issues nothing to do with the code.

**Comment by zkat** [comment]
I'm gonna want to review this with @iarna before merging.

**Comment by aukevanleeuwen** [comment]
I'm not really in favor of `+1` like comments, but in this case: I'm really really looking forward to this fix since it seems to match my case exactly. 

--
Also wanted to link https://github.com/npm/npm/issues/13528 because that's where my quest started out some time ago. I know the repo is archived, but maybe that issue still gets a reference automatically.

**Comment by zoellner** [comment]
To anyone who ends up here from https://github.com/npm/npm/issues/13528 and if you've run across this problem just recently: - this error recently showed up a lot because of a pulled package with a vulnerability. See https://github.com/dominictarr/event-stream/issues/116 for details.

**Comment by stevebaxter** [comment]
Is there a workaround for this? This has completely screwed our project right now.

**Comment by jtwebman** [comment]
@iarna Could we get a review on this so @zkat can merge this.

**Comment by sahellebusch** [comment]
I'm going to echo others here since this isn't budging. This is a breaking change that is problematic to many developers. Yes, a major version, but just as JS is always backwards compatible, I would imagine the package manager would be as well. I know there are arguments for how this _should_ be done, but for the time being this should be merged to fix the immediate needs of those who are facing the same challenges and cannot upgrade to the latest npm version.

**Comment by baptistemarchand** [comment]
@zkat @iarna are there any issues blocking this from being merged?

It looks like it would solve issues for many users.

Thanks!

**Comment by jmacek** [comment]
I would like to vote for this being merged soon please, this has been an issue for my team as well.

Thanks

**Review by zkat — APPROVED** [review]
I'm gonna approve this -- tests look ok, and the code is from #40, which has been pending for a while now. Cheers!

**Comment by baptistemarchand** [comment]
Hello,
Will this change be included in the next release? (on February 6th)
Thanks!

**Comment by jbinard** [comment]
Please add this fix in the next release, this is a real issue for my team.

Thanks!

**Comment by aeschright** [comment]
Could you do a quick rebase? Looks like you pulled in an earlier changelog commit.

**Comment by baptistemarchand** [comment]
Just (another) quick bump to make sure this gets released tomorrow :)
Thanks!

**Comment by orwell1984** [comment]
Chiming in as it seems to be the source of issues for my project as well.

**Comment by aeschright** [comment]
Thanks for working with us to get this done! It's in today's pre-release and you can test it out: https://npm.community/t/release-npm-6-8-0-next-2/5199

**Comment by jfirebaugh** [comment]
Now `npm ci` is not working with local dependencies: https://npm.community/t/6-8-0-npm-ci-fails-with-local-dependency/5385

**Comment by MaximeCheramy** [comment]
We have a project that depends on a local node module that has itself some dependencies. `npm install` installs the local module and its dependencies. However, in the package-lock.json, the dependencies of the local module are no longer listed and `npm ci` doesn't install them.

It was working with npm 6.7.0.

**Comment by joual** [comment]
Seems like this broke some functionality of NPM ci. See https://npm.community/t/6-8-0-npm-ci-fails-with-local-dependency/5385/3?u=joual

**Comment by joual** [comment]
@zkat Could you enlighten us on whether the issue is with the package-lock.json not having `dependencies` for local files, or if it's with libcipm failing when it can't find a `dependencies` key for these? I'm trying to understand the intent in this PR and @iarna's commits seem to explicitly _want to prevent dependencies from being generated_ i.e. 381c55e

I'd be inclined to look into this a bit more and contribute if I can (even though I lack a lot of knowledge wrt npm's internals) but just trying to figure out where to start.

**Pull request merged**
