### PR TITLE
Fully automate dev setup with Gitpod

### PR DESCRIPTION
**Pull request by ghost**
This commit implements a fully-automated development setup using Gitpod.io, an
online IDE for GitLab, GitHub, and Bitbucket that enables Dev-Environments-As-Code.
This makes it easy for anyone to get a ready-to-code workspace for any branch,
issue or pull request almost instantly with a single click.

Remove all my api’s and reset all my accounts and balance to zero. Since, I was bugged and hacked.

Thank you I really appreciate all the hard work and effort.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
nice

**Comment by ghost** [comment]
> This commit implements a fully-automated development setup using Gitpod.io, an
> online IDE for GitLab, GitHub, and Bitbucket that enables Dev-Environments-As-Code.
> This makes it easy for anyone to get a ready-to-code workspace for any branch,
> issue or pull request almost instantly with a single click.

Thanks for help and support they got what they deserve, kindly help me to remove all api’s and reset all my account and balance to zero  (0).

**Comment by ghost** [comment]
Thanks for help and support they got what they deserve, kindly help me to remove all api’s and reset all my account and balance to zero  (0).

**Comment by ghost** [comment]
> This commit implements a fully-automated development setup using Gitpod.io, an
> online IDE for GitLab, GitHub, and Bitbucket that enables Dev-Environments-As-Code.
> This makes it easy for anyone to get a ready-to-code workspace for any branch,
> issue or pull request almost instantly with a single click.

Thanks for help and support they got what they deserve, kindly help me to remove all api’s and reset all my account and balance to zero  (0).

**Comment by ghost** [comment]
Remove all my api’s and reset all my accounts and balance to zero. Since, I was bugged and hacked.

Thank you I really appreciate all the hard work and effort.

**Comment by ghost** [comment]
Thanks for the help and efforts, please remove all api's and reset my accounts and balance to zero (0). Since, I was bugged or hacked.

**Comment by ljharb** [comment]
Duplicate of #3622.

**Pull request closed without merging**
