### PR TITLE
feat: sort and quote yarn lock keys according to yarn rules

### PR DESCRIPTION
**Pull request by wraithgar**
This PR adjusts the logic used for sorting keys when writing yarn.lock to be more in line with Yarn's own rules, avoiding unnecessary diffs and confusion.

This adds a commit to https://github.com/npm/cli/pull/5659

Please squash

### CODE REVIEW

**Review by lukekarrys — APPROVED** [review]

**Comment by shalvah** [comment]
@wraithgar I see this was released, but the [yarn-lock file on latest](https://github.com/npm/cli/blob/latest/workspaces/arborist/lib/yarn-lock.js) has none of the changes or commits. Was it removed?

**Comment by wraithgar** [comment]
9.0.0 is not tagged as latest yet

**Comment by cachius** [comment]
Re:tagged as latest - The strategy is explained [here](https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/)
>Wednesday Nov. 9th (General Availability) ...
npm@9.x will be set to the latest dist-tag (becoming the latest, maintained version of npm)
<br>

@wraithgar Are you sure it is in the source, though? Visiting https://github.com/npm/cli/commit/64a19d05fcf840d10ef0c8c4617565413266a02d yields the warning
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

Not sure if this relates to the tagging.

**Comment by wraithgar** [comment]
You're right, something funky happened here during the release, cc @lukekarrys

**Comment by wraithgar** [comment]
I had the branch locally still, pushed and made a pr https://github.com/npm/cli/pull/5751

**Pull request merged**
