### PR TITLE
fix(perf): avoid importing the entire semver package for update-notifier

### PR DESCRIPTION
**Pull request by H4ad**
There are a bunch of places were we load `semver`, I'm trying to see if I can remove the full import for `semver` and only import the specific functions.

Currently, I didn't have any perf improvement since we still load the entire `semver`, once we have removed all the package loads, then we could see some improvement (a little bit).

### CODE REVIEW

**Comment by lukekarrys** [comment]
Update notifier is often skipped due to config or if it has been run recently. In addition to this, do you think we should lazy load all the requires in this file?

**Comment by H4ad** [comment]
@lukekarrys, if you think it will not hurt the maintainability, lazy loading everything will save  ~`300us`.

Most of the `require` is already in the cache, so the impact is very minimal of having them at the top of the file.

**Comment by wraithgar** [comment]
The update notifier, as far as I can remember, is called in a completely asynchronous way that gracefully handles a situation where the npm command is done before it finishes.  Optimizing it is probably not needed.

If you find a situation where the update notifier is blocking the event loop, causing npm to not exit if the command is already finished, that is an actionable situation.  Otherwise it's probably not worth the effort.

**Comment by H4ad** [comment]
>  is called in a completely asynchronous way

The `require` is synchronous, even if we do not wait the return value.

About this module, just refactoring the imports for `semver` currently is enough.

**Comment by lukekarrys** [comment]
I also want to note that this may cause fluctuations in benchmarking. You can add `--no-update-notifier` to you benchmarking command to ensure these lazy requires are never called.

**Review by lukekarrys — APPROVED** [review]

**Pull request merged**
