### PR TITLE
install: add support for package aliases

### PR DESCRIPTION
**Pull request by zkat**
## TODO

* [x] basic implementation
* [x] fix `npm i` printouts
* [x] fix `npm ls` display
* [x] fix `npm outdated` and `npm update` support
* [x] land https://github.com/iarna/lock-verify/pull/3
* [x] check that cipm works, too
* [x] fix failing tests
  * [x] `ignore-install-link.js`
  * [x] `404-parent.js`
  * [x] `00-verify-ls-ok.js`
  * [x] `check-install-self.js`
  * [x] `dedupe-scoped.js`
  * [x] `do-not-remove-other-bins.js`
  * [x] `gently-rm-linked-module.js`
  * [x] `gently-rm-symlinked-global-dir.js`
  * [x] `install-actions.js`
  * [x] `install-at-sub-path-locally.js`
  * [x] `install-contributors-count.js`
  * [x] `install-into-likenamed-folder.js`
  * [x] `install-report-just-installed.js`
  * [x] `install-scoped-already-installed.js`
  * [x] `legacy-ignore-nested-rm.js`
  * [x] `legacy-test-package.js`
  * [x] `link.js`
  * [x] `ls-l-depth-0.js`
  * [x] `ls-peer.js`
  * [x] `ls.js`
  * [x] `shared-linked.js`
  * [x] `shrinkwrap-default-dev.js`
  * [x] `spec-local-specifiers.js`
  * [x] `symlink-cycle.js`
  * [x] `test/network/legacy-bundled-git.js`
  * [x] `uninstall-link-clean.js`

### CODE REVIEW

**Review by aeschright — APPROVED** [review]
🕵️‍♀️! Looks good!

**Comment by hinell** [comment]
Where we can find documentation on these?

**Comment by hinell** [comment]
Where we can find documentation on this?

**Comment by benmonro** [comment]
docs or even a comment here with an example would be nice, i'm curious what this feature is all about...

**Comment by chee** [comment]
hey, @hinell and @benmonro. you can read more about this feature in the RFC for package aliases

https://github.com/npm/rfcs/blob/latest/implemented/0001-package-aliases.md

**Comment by hinell** [comment]
@chee Thanks for the link.

Looks like this feature doesn't work. When I attempt to use `npm i package@npm:express` I get error:
<details>
<summary>Unwrap</summary>

```Unhandled rejection Error: Invalid tag name "serve@npm:serve-static": Tags may not have any characters that encodeURIComponent encodes.
    at invalidTagName (E:\Programs\NodeJS\node_modules\npm\node_modules\npm-package-arg\npa.js:87:15)
    at fromRegistry (E:\Programs\NodeJS\node_modules\npm\node_modules\npm-package-arg\npa.js:290:13)
    at Function.resolve (E:\Programs\NodeJS\node_modules\npm\node_modules\npm-package-arg\npa.js:77:12)
    at doesChildVersionMatch (E:\Programs\NodeJS\node_modules\npm\lib\install\deps.js:75:25)
    at exports.earliestInstallable (E:\Programs\NodeJS\node_modules\npm\lib\install\deps.js:800:10)
    at addBundled (E:\Programs\NodeJS\node_modules\npm\lib\install\deps.js:653:20)
    at addBundled (E:\Programs\NodeJS\node_modules\npm\lib\fetch-package-metadata.js:90:78)
    at isInstallable (E:\Programs\NodeJS\node_modules\npm\lib\install\deps.js:652:5)
    at checkPlatform (E:\Programs\NodeJS\node_modules\npm\node_modules\npm-install-checks\index.js:53:10)
    at thenWarnEngineIssues (E:\Programs\NodeJS\node_modules\npm\lib\install\validate-args.js:52:5)
    at a (E:\Programs\NodeJS\node_modules\npm\node_modules\iferr\iferr.js:3:64)
    at checkEngine (E:\Programs\NodeJS\node_modules\npm\node_modules\npm-install-checks\index.js:24:10)
    at module.exports.isInstallable (E:\Programs\NodeJS\node_modules\npm\lib\install\validate-args.js:49:3)
    at resolveWithNewModule (E:\Programs\NodeJS\node_modules\npm\lib\install\deps.js:650:10)
    at E:\Programs\NodeJS\node_modules\npm\lib\install\deps.js:245:5
    at E:\Programs\NodeJS\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
```

</details>

My **platform** is Windows 10 x64
npm: 6.7.0
node: v11.14.0

**Comment by ljharb** [comment]
@hinell the feature is in v6.9 of npm, you have v6.7.

**Comment by hinell** [comment]
@ljharb Oh thank you!

**Comment by mikkorantalainen** [comment]
Documentation at https://github.com/npm/rfcs/blob/latest/implemented/0001-package-aliases.md mentions that this implementation 

> will NOT address ... replacing packages in **transitive dependencies** that have different names (`npm i underscore@npm:lodash` will only make it so `require('underscore')` in your own project loads `lodash` instead. _Your dependencies_ will receive their own (nested) version of the _actual_ underscore package). This may be covered in the future by an explicit resolutions mechanism, and may be facilitated by this RFC, but is still not part of it.

Are the any current plans for allowing aliasing packages in the **transitive dependencies**? I have a more specific question about this at https://stackoverflow.com/q/64121161/334451

**Pull request merged**
