### PR TITLE
Always save package_lock.json when using `--package-lock-only`

### PR DESCRIPTION
**Pull request by aeschright**

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
Instead of throwing, is there some reason that `--package-lock-only` can't *imply* `--package-lock`?

**Comment by ljharb** [comment]
My use case is:
1. i always set `package-lock=false` in my .npmrc, because i don't believe non-apps should ever have lockfiles
1. `npm audit` requires a lockfile
1. i have scripts that do `npm install --package-lock --package-lock-only` in a script prior to running `npm audit`, to work around this omission
and it'd be nice to avoid the seemingly redundant `--package-lock` :-)

**Comment by iarna** [comment]
Just implying package-lock doesn't seem outrageous, and as you're our biggest window into `--no-package-lock` users and you want this, I'm inclined to say that we should do that.

**Comment by ljharb** [comment]
to be clear, i also think `npm audit` should be able to do these steps for me when there's no package-lock present, but either way i think `--package-lock-only` implying `--package-lock` makes sense :-)

Thanks!

**Comment by aeschright** [comment]
Makes sense to me!

**Review by zkat — APPROVED** [review]

**Pull request merged**
