### PR TITLE
fix(deprecate): ignore implicit workspace mode

### PR DESCRIPTION
**Pull request by wraithgar**

### CODE REVIEW

**Comment by wraithgar** [comment]
May need test updates, making the PR now so it gets in my workflow.

**Comment by lukekarrys** [comment]
Is this in reference to an open issue? I'm missing some context about what this changes when running `npm deprecate` I think.

**Comment by wraithgar** [comment]
This was in response to a support ticket. If someone is inside a workspace this command doesn't work.    This command requires you to specify a package name, it never infers it from cwd.  So, whether or not you're inside a workspace is irrelevant.

**Review by lukekarrys — APPROVED** [review]

**Comment by lukekarrys** [comment]
:shipit:  thanks for reminding me what `ignoreImplicitWorkspace` does 😄

**Pull request merged**
