### PR TITLE
Add npm audit resolve command

### PR DESCRIPTION
**Pull request by naugtur**
Add means for a human to resolve issues if they can't be fixed and interactively make decisions about each issue.

See https://npm.community/t/interactive-tool-to-manage-audit-findings-npm-audit-resolve/197

I'm still hoping to discuss this, as I assume I'm not aware of all npm-cli features and modes of operation.

TODO:

 - [ ] (partially done) add handling of npm configuration like `prefix` that I don't know how to do as of now
 - [x] make npm audit use the audit-resolv.json if present 
 - [x] fix node6 support (a dependency is using `...` syntax)

### CODE REVIEW

**Comment by zkat** [comment]
Hey @naugtur! We just met to talk about this stuff and how to handle this PR. The conclusion is a couple of points:

1. This is definitely the sort of thing we want, and it's really awesome that you took the initiative to do this. It was already on our roadmap, so it does get some level of priority. Thank you!
1. This needs a full-fledged RFC and some back-and-forth discussions between you, @evilpacket, and @iarna, so we can suss out all the little decisions and details for this thing's behavior.
1. The client library should live under [the npm github org](https://github.com/npm) for what we consider to be security reasons, and follow our standard repo practices (which we can help you set up). Obvs, you'd be given write access to that repo :)
1. I'm going to close this specific PR because of the above decisions that need to be made, and I look forward to getting this feature into the CLI!

**Comment by naugtur** [comment]
Sounds legit.
I'll start the RFC in a day or two.

It'd be nice, since it's an interactive tool, to get some feedback from people using it in the wild. I wonder how to put my early version in front of some people as a trusted-tester stage for the resolver. 
I'll include that concern in the RFC, let's not keep this thread going here.

**Comment by dead-claudia** [comment]
@naugtur Could you post a comment here once you've done that, so I can subscribe to the RFC discussion?

**Comment by naugtur** [comment]
Sure, I wanted to have it posted already, but it's a little intimidating and I feel like I need to write a lot :)

**Comment by naugtur** [comment]
The RFC is up. Hope it was worth the wait...
https://github.com/npm/rfcs/pull/18

cc @isiahmeadows

**Pull request closed without merging**
