### PR TITLE
Fixes issue with preversion script exposing the new updated package information instead of the currently existing one

### PR DESCRIPTION
**Pull request by luislobo**
Fixes issue with preversion script exposing the new updated package information instead of the currently existing one

Addresses issue described in https://npm.community/t/npm-version-preversion-npm-package-version/1406

### CODE REVIEW

**Review by zkat — APPROVED** [review]
Looks good to me. Thank you!

I believe this will be a semver-major change, so I'm gonna keep this PR open until `npm@7` is ready to go out, and it should go in with that. Cheers!

**Comment by luislobo** [comment]
@zkat Cool, thanks! In the meantime, I'm adding manual support in our `preversion` scripts, reading the `package.json` file, as the file do have the current version.

**Comment by luislobo** [comment]
@zkat Don't forget about this one ;)

**Comment by luislobo** [comment]
@zkat Friendly reminder about this PR

**Comment by chee** [comment]
@luislobo it's labeled as `semver:major` so they probably won't be looking at it until the next major version of npm is ready to go out, but they'll see it then! 😊

**Comment by luislobo** [comment]
@isaacs Any news on getting this merged? We have had to workaround this issue reading the file ourselves to get the real information

**Comment by JanithaR** [comment]
It's 2020 March already. Any particular reason why this isn't already merged?

**Comment by ljharb** [comment]
Because it's a semver-major change, and npm 7 hasn't gone out yet?

**Comment by JanithaR** [comment]
> Because it's a semver-major change, and npm 7 hasn't gone out yet?

I ask stupid questions. :) But man this should've been a patch.

**Comment by luislobo** [comment]
@isaacs is this going to be included in npm 7?

**Comment by isaacs** [comment]
So, _this_ patch won't be in v7, because that section of code has been rewritten, and `npm-lifecycle` is being put to bed for the long sleep of deprecated modules.

But here's what the `preversion` environment looks like in v7, which I think satisfies the need that this is addressing:

```
$ cat package.json
{
  "name": "name",
  "version": "1.2.4",
  "scripts": {
    "preversion": "env | grep npm_"
  }
}

$ node ../cli version patch
> name@1.2.4 preversion
> env | grep npm_
npm_config_metrics_registry=https://registry.npmjs.org/
npm_new_version=1.2.5
npm_old_version=1.2.4
npm_execpath=/Users/isaacs/dev/npm/cli/lib/npm.js
npm_config_access=public
npm_package_json=/Users/isaacs/dev/npm/foo/package.json
npm_command=version
npm_lifecycle_event=preversion
npm_config_node_gyp=/Users/isaacs/dev/npm/cli/node_modules/@npmcli/run-script/node_modules/node-gyp/bin/node-gyp.js
npm_lifecycle_script=env | grep npm_
npm_config_user_agent=npm/7.0.0-beta node/14.2.0 darwin x64
npm_node_execpath=/usr/local/bin/node
1.2.5
```

Let me know if there's more to do here, or if this meets your need.  Thanks!

**Comment by luislobo** [comment]
Looks good to me!

**Pull request closed without merging**
