### PR TITLE
Added ARM64 platform check 

### PR DESCRIPTION
**Pull request by ossdev07**
I have added the arm64 architecture check in the legacy-platform-all.js test file.

### CODE REVIEW

**Comment by ossdev07** [comment]
Ping @luislobo @aeschright 

Please, could you look into PR and suggest if anything else is required from my side.

**Comment by rhenwood-arm** [comment]
I would be nice for me (as an AArch64 aka Arm64 user) if this small fix was landed. Is there any feedback?

**Comment by ossdev07** [comment]
Hi, @luislobo @aeschright 

Is there any update on the PR status?

**Comment by aeschright** [comment]
Unfortunately, I'm no longer on the project and don't know when PRs will be merged again. Details: https://gist.github.com/aeschright/8ed09cbc2a4aee00fcb4ad35086d76a6

**Comment by ossdev07** [comment]
@aeschright Thanks for letting us know.

**Comment by DanielRuf** [comment]
Is this already merged?

**Comment by ossdev07** [comment]
Thanks for accepting the PR, it got merged by the raised PR https://github.com/npm/cli/pull/205

**Pull request closed without merging**
