### PR TITLE
fix(view): sort and truncate dist-tags

### PR DESCRIPTION
**Pull request by wraithgar**
This sorts dist-tags by publish date so that newer tags show first,
giving top priority to the `latest` tag.

It also truncates the list in a similar manner to how dependencies are
truncated.

Needs tests.

Before: 
dist-tags list in npm view showing every tag shorted by version

After:
dist-tags list in npm view showing a truncated list sorted by publish date

### CODE REVIEW

**Comment by wraithgar** [comment]
This potentially has some overlap with https://github.com/npm/cli/pull/7807.

**Comment by wraithgar** [comment]
A better example of why this helps is via the output of `npm view gatsby`

Before:
more dist-tags than can even fit on one screen

After:
the 24 newest dist-tags only

**Comment by ruyadorno** [comment]
Love it! :shipit:

**Comment by wraithgar** [comment]
Looks like I got too clever trying to do fallback sorting, it confuses the algorithm:

npm's dist tags showing random sorting of versions w/ multiple tags

**Review by reggi — APPROVED** [review]

**Pull request merged**
