### PR TITLE
fix(pack): detect unresolved package properly

### LINKED ISSUE #3132: [BUG] pack wrongly errors with npm@7.11.0
### Current Behavior:

With npm@7.11.0 we see problems with some scripts that use `npm pack`, it works without a problem on npm@7.10.0
It errors recently with `Invalid package, must have name and version`, while it worked before without a problem.

### Expected Behavior:

`npm pack` to work as before 

### Steps To Reproduce:

```shell
$ npm i -g npm@7.10.0
$ npm pack ory-prettier-styles@1.1.2
npm notice 
npm notice 📦  ory-prettier-styles@1.1.2
npm notice === Tarball Contents === 
npm notice 11.4kB CONTRIBUTING.md                          
npm notice 11.4kB LICENSE                                  
npm notice 418B   README.md                                
npm notice 1.4kB  SECURITY.md                              
npm notice 92B    .github/FUNDING.yml                      
npm notice 515B   .github/ISSUE_TEMPLATE/bug_report.md     
npm notice 538B   .github/ISSUE_TEMPLATE/config.yml        
npm notice 563B   .github/ISSUE_TEMPLATE/feature_request.md
npm notice 187B   .github/semantic.yml                     
npm notice 718B   .github/workflows/closed_references.yml  
npm notice 473B   .github/workflows/labels.yml             
npm notice 1.2kB  .github/workflows/publish.yml            
npm notice 302B   .github/workflows/release_tagger.yml     
npm notice 1.1kB  .github/workflows/stale.yml              
npm notice 338B   .github/workflows/test.yml               
npm notice 34B    .reference-ignore                        
npm notice 712B   package.json                             
npm notice 177B   prettier.config.js                       
npm notice 174B   prettier.config.ts                       
npm notice 59B    tsconfig.json                            
npm notice === Tarball Details === 
npm notice name:          ory-prettier-styles                     
npm notice version:       1.1.2                                   
npm notice filename:      ory-prettier-styles-1.1.2.tgz           
npm notice package size:  12.0 kB                                 
npm notice unpacked size: 31.7 kB                                 
npm notice shasum:        750a35ab29d09ae1a95173ff6d11f70ec262aaaa
npm notice integrity:     sha512-J7YcNdGlfTKCX[...]uKWhZeaeb6Z/A==
npm notice total files:   20                                      
npm notice 
ory-prettier-styles-1.1.2.tgz

$ npm i -g npm@7.11.0
$ npm pack ory-prettier-styles@1.1.2
npm ERR! Invalid package, must have name and version

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/patrik/.npm/_logs/2021-04-23T12_30_35_771Z-debug.log

$ cat /home/patrik/.npm/_logs/2021-04-23T12_30_35_771Z-debug.log
0 verbose cli [
0 verbose cli   '/home/patrik/.nvm/versions/node/v14.15.5/bin/node',
0 verbose cli   '/home/patrik/.nvm/versions/node/v14.15.5/bin/npm',
0 verbose cli   'pack',
0 verbose cli   'ory-prettier-styles@1.1.2'
0 verbose cli ]
1 info using npm@7.11.0
2 info using node@v14.15.5
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/home/patrik/.nvm/versions/node/v14.15.5/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/patrik/git/keto/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/home/patrik/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/patrik/.nvm/versions/node/v14.15.5/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 9ms
18 timing npm:load:configload Completed in 9ms
19 timing npm:load:setTitle Completed in 0ms
20 timing npm:load:setupLog Completed in 2ms
21 timing npm:load:cleanupLog Completed in 3ms
22 timing npm:load:configScope Completed in 0ms
23 timing npm:load:projectScope Completed in 0ms
24 timing npm:load Completed in 16ms
25 timing config:load:flatten Completed in 3ms
26 timing command:pack Completed in 24ms
27 verbose stack Error: Invalid package, must have name and version
27 verbose stack     at Pack.pack (/home/patrik/.nvm/versions/node/v14.15.5/lib/node_modules/npm/lib/pack.js:57:15)
28 verbose cwd /home/patrik/git/keto
29 verbose Linux 5.10.30-1-MANJARO
30 verbose argv "/home/patrik/.nvm/versions/node/v14.15.5/bin/node" "/home/patrik/.nvm/versions/node/v14.15.5/bin/npm" "pack" "ory-prettier-styles@1.1.2"
31 verbose node v14.15.5
32 verbose npm  v7.11.0
33 error Invalid package, must have name and version
34 verbose exit 1
```

### Environment:

see steps above

Thanks a lot :heart:

### PR DESCRIPTION
**Pull request by zepatrik**
See bug report in #3132
The test case was failing before adjusting the check.

## References

Fixes #3132

### CODE REVIEW

**Comment by wraithgar** [comment]
We'd prefer if the test didn't make real network calls if possible.  Not sure what's happening here, read-package-json-fast adds this to the manifest, and pacote uses that to parse package.json files:

https://github.com/npm/pacote/blob/latest/lib/file.js#L29

https://github.com/npm/read-package-json-fast/blob/master/index.js#L32-L36

```js
const add_id = data => {
  if (data.name && data.version)
    data._id = `${data.name}@${data.version}`
  return data
}
```

**Comment by zepatrik** [comment]
Hm interesting, I did not check other packages but the one I have here is returned by pacote without `_id`...
I will close this PR then, as it probably needs an upstream fix.

**Comment by wraithgar** [comment]
The root cause is that npm-pick-manifest returns different data than read-package-json-fast.  We're discussing it to see what path to take.

**Review by RonSherfey — COMMENTED** [review]
changes reviewed

**Pull request closed without merging**
