### PR TITLE
fix: move all definitions to @npmcli/config package

### PR DESCRIPTION
**Pull request by lukekarrys**
~~This builds on #6490 to avoid conflicts with the config changes there.~~

~~Marking this as a draft until that lands, then this can be rebased if necessary and marked as ready for review.~~

This is ready

### CODE REVIEW

**Comment by matz3** [comment]
@lukekarrys does this PR change the fundamental message of the package?
> It does the management of configuration files that npm uses, but importantly, does _not_ define all the configuration defaults or types, as those parts make more sense to live within the npm CLI itself.

We're looking for the best approach to move from `libnpmconfig` to `@npmcli/config` for a use case where we download packages via `pacote` and want to ensure to take the user configuration into account.

**Comment by lukekarrys** [comment]
> does this PR change the fundamental message of the package?

good catch! yes, with this change that statement is no longer true. we've found it is best to have all the config definitions live alongside the logic in `@npmcli/config`.

i haven't taken a look at updating the docs yet, since i have a larger refactor in process that will contain a few breaking changes, and was updating the documentation in that branch.

this PR is a stop-gap to implement the diff-heavy work of moving the config files, without changing anything about the implementation.

> We're looking for the best approach to move from libnpmconfig to @npmcli/config

one of the goals of the next major version, will be to limit what is required to be passed in to `new Config(opts)`, so that should be helpful to your use case. i don't have any definitive timeline yet for when that might land yet.

**Review by wraithgar — APPROVED** [review]
We're getting close!

**Comment by d3xter666** [comment]
Hi @lukekarrys,

Do you plan a new release with those changes?

Cheers

**Pull request merged**
