### PR TITLE
updated policy urls - v7

### PR DESCRIPTION
**Pull request by demiracl**
Updated Policy urls to point to Docs v7

### CODE REVIEW

**Comment by wraithgar** [comment]
Those urls currently 404

**Comment by wraithgar** [comment]
Converting to draft so we can visually see that this isn't ready till those urls exist.

**Comment by demiracl** [comment]
The urls in this PR depend on the documentation PR - https://github.com/npm/documentation/pull/20 to be merged, so they resolve

**Review by wraithgar — APPROVED** [review]
Spot checked the urls they seem to be working now.

**Pull request merged**
