### PR TITLE
CI: fix license OS check

### PR DESCRIPTION
**Pull request by XhmikosR**
Might conflict with #2531, if so ping me to rebase.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Hmm, maybe this is a leftover after all? It seems the licensee dev dependency is not present anymore.

**Comment by ljharb** [comment]
licensee should definitely still be used by npm - as a prod dep tho.

**Comment by XhmikosR** [comment]
Weird, right now it seems it's not present. I marked the PR as draft until
we figure this out.

**Comment by ljharb** [comment]
This has been addressed as part of #2654.

**Pull request closed without merging**
