### PR TITLE
feat: add --iwr alias for --include-workspace-root

### PR DESCRIPTION
**Pull request by fritzy**
Added a shorthand form of `--include-workspace-root` as `--iwr`.

### CODE REVIEW

**Review by nlf — APPROVED** [review]
this could maybe use docs somewhere, but the change looks good

**Review by missionzero316 — COMMENTED** [review]
tap-snapshots/test/lib/utils/config/index.js.test.cj

**Review by missionzero316 — COMMENTED** [review]
tap-snapshots/test/lib/utils/config/index.js.test.cjslib/utils/config/index.jsdocs/content/using-npm/config.md

**Comment by mesqueeb** [comment]
@fritzy @nlf can you add this to the docs? 🙇🏻  and is it `--iwr` or `-iwr`?

**Pull request merged**
