### PR TITLE
deps: meant@1.0.2

### PR DESCRIPTION
**Pull request by watilde**
Bump the version of meant

Updates:
+ Bump dev deps versions
+ Replace travis with GitHub Actions

Refs: https://github.com/watilde/meant/blob/master/CHANGELOG.md#102-2020-07-19

### CODE REVIEW

**Comment by ljharb** [comment]
replacing Travis is a massive change that both should happen in its own commit, and its own pr

**Comment by watilde** [comment]
@ljharb Yes, and it is separated in [the dependency's repository](https://github.com/watilde/meant). Did you mean it should be major update in terms of semver? I can bump major version in that case.

**Comment by ljharb** [comment]
@watilde sorry, what i meant is, updating "how CI works" in *this repo* is something that deserves its own PR. Updating `meant` is a small change that shouldn't be conflated with changing this repo's CI setup.

**Comment by watilde** [comment]
@ljharb Got it! Thank you for your clear explanation and review<3

**Review by ruyadorno — APPROVED** [review]

**Pull request closed without merging**
