### PR TITLE
Check run script existence with undefined

### PR DESCRIPTION
**Pull request by vlasy**
Makes it possible to run empty script instead of outputting slightly confusing error message.

In `package.json`:
```
"scripts": {
    "empty": ""
  },
```

Before
```
> npm run empty
npm ERR! missing script: empty
npm ERR!
npm ERR! Did you mean this?
npm ERR!     empty

npm ERR! A complete log of this run can be found in:
...
>
```

After
```
> npm run empty
> 
```

### CODE REVIEW

**Comment by aeschright** [comment]
Did this come from a discussion you can point me to? Or can you describe the underlying use case it would solve?

**Comment by vlasy** [comment]
I was running one of my projects through some automated build tools which needed specific npm scripts to exist. In this project, there was no need for that script to run so I created an empty npm script, hoping it would solve the problem. But then I got the error message shown above.

I could not find any discussion about this situation and the change was rather small, so I went straight to PR.

**Review by zkat — CHANGES_REQUESTED** [review]
This seems like a reasonable allowance -- but I can't really review the changes you made, because this needs to be rebased onto `latest`. See how "Files changed" says `938` 🙃 .

**Comment by vlasy** [comment]
Rebased :)

**Comment by vlasy** [comment]
Hi @zkat , is there anything else I can do? PR is rebased now :)

**Review by zkat — APPROVED** [review]
Everything looks good now! Thanks a bunch. :)

**Pull request merged**
