### PR TITLE
feat: add `preinstallOnly` script

### PR DESCRIPTION
**Pull request by hirehamir**

### CODE REVIEW

**Comment by hirehamir** [comment]
# What / Why

`preinstall` doesn't actually run before installation. This pull request adds a `preinstallOnly` script that should run before installation, although I haven't been able to test it with a `package.json` that has a `preinstallOnly` script, and I would like to.

**Comment by hirehamir** [comment]
I got the idea to use `preinstallOnly` from https://github.com/npm/cli/issues/2660#issuecomment-794367530.

> you're not wrong, to be honest a lot of our lifecycle scripts are poorly named and don't run exactly when you expect. that's why there's both a `prepublish` and a `prepublishOnly`. we have a lot of technical debt here, but changing the expectations about how lifecycle scripts work is a glacier of a breaking change.
> 
> the best we can do right now is clearly document when scripts run and what's available to them

**Comment by wraithgar** [comment]
This would constitute a breaking change and would have to wait till npm 11

**Comment by ljharb** [comment]
Why would a new script be a breaking change?

**Comment by wraithgar** [comment]
Ah my oversight, I thought this was moving an existing script

**Comment by hirehamir** [comment]
I was able to test it out locally just now, and it appears to work as intended.

**Comment by hirehamir** [comment]
https://github.com/npm/cli/assets/43425812/4fbb337f-ee26-4f6e-a2e4-70089447d924

**Comment by MattCCC** [comment]
Works well on mine.

**Comment by nkamenar** [comment]
Any word on when this will release? My team is switching to pnpm also and running into exactly this problem where someone accidentally runs npm install and we can't prevent it.

**Comment by hirehamir** [comment]
@wraithgar what changes would you like this pull request to have, to consider merging it?

**Comment by wraithgar** [comment]
This is a great contribution and it seems to fit into a point of the install lifecycle that might not be fully covered yet. Our team is currently reviewing the npm lifecycle hooks as a whole and the best resolutions for it moving forward.

Unfortunately this means we won't be able to accept this new feature knowing it may eventually be affected by a breaking change.

**Comment by hirehamir** [comment]
Okay, thanks for the explanation.

**Pull request closed without merging**
