### PR TITLE
chore: @npmcli/template-oss@4.19.0

### PR DESCRIPTION
**Pull request by lukekarrys**

### CODE REVIEW

**Review by wraithgar — APPROVED** [review]

**Comment by lukekarrys** [comment]
We should land this because it doesn't make the CI failures worse, but it also doesn't fix the issue with running `node scripts/resetdeps.js` in Node 14. It is running the correct version of `npm` for Node 14, but once it drops down to that script there will always be an error due to it using Node 16 only features.

It seems easiest to bump all workspace engines to `^16.14 || >= 18'. @wraithgar what do you think?

**Comment by wraithgar** [comment]
I think the npm workspaces are going to have to come along with npm in their engines declarations.

**Review by wraithgar — APPROVED** [review]

**Comment by lukekarrys** [comment]
This should now be rebased. It includes two breaking changes for updating the engines on `@npmcli/config` and `libnpmfund`. It also uses template-oss to configure the engines for both so in the future we will be forced to update the workspace engines all at once.

**Comment by lukekarrys** [comment]
There should be no more expected CI failures in this PR. If any runs fail they should be examined and fixed.

**Pull request merged**
