### PR TITLE
feat: add alias I(capital i) for install.

### PR DESCRIPTION
**Pull request by zhangenming**
Make the following accidentally typed input more convenient.
887187ec546e8fa33d10d44349cf707

### CODE REVIEW

**Comment by wraithgar** [comment]
Thanks for your contribution. At this time we are not going to alias every command to be case insensitive.

**Comment by zhangenming** [comment]
I beg you to reconsider.

Shouldn't there be any harm in adding him (If there is, I'd like to know what)
However, it can resolve some cases of re-entry
I think it's useful (2 bodys reacted with heart emoji)
tanks

**Comment by zhangenming** [comment]
Since `npm i` is a very common command, I think special consideration should be given to him

**Comment by ljharb** [comment]
It’s only in windows systems that the command name is case insensitive, i believe - most users would get an error regardless, because the binary is named “npm”

**Comment by zhangenming** [comment]
yes, 
But this PR still helpfulness for windows user

**Comment by wraithgar** [comment]
It is not as helpful as you think, it allows folks to type incorrect syntax without them every knowing it is incorrect.  It's much better in the long run to enforce the correct syntax.

There are many commands that will either not work or work in unexpected ways if folks assume they are case insensitive.  Package names are a good example.  Even though we don't allow capital letters anymore the package name is case sensitive.  There are a few very old legacy packages also that contain upper case letters so we can't just force the package names to be lower case.  Usernames have similar problems.

In the long run it is a bad idea to silently correct user errors.  Much better to just error and let them correct their syntax.

**Comment by zhangenming** [comment]
THANK YOU

But why do these things exist , and what does it different with `I`
I didn't want to send this pr UNTIL I saw these
These things give me confidence
image

**Comment by wraithgar** [comment]
Those have existed for many years, and were added in a time when npm was trying to be "helpful".  We have learned over the many years of developing npm that this is not a good idea, and will not be adding any more.  We also plan to eventually remove the typo affordances.

**Comment by zhangenming** [comment]
thank you sir

**Pull request closed without merging**
