### PR TITLE
release: npm@6.2.0

### PR DESCRIPTION
**Pull request by zkat**
[Rendered Changelog](https://github.com/npm/cli/blob/7a08a9b344a1363cc96ee989d7640252db065653/CHANGELOG.md)

### CODE REVIEW

**Comment by ljharb** [comment]
the changelog link doesn't seem to point anywhere?

**Comment by sharmilajesupaul** [comment]
not sure what's going on with the URL but I'm able to see: https://github.com/npm/cli/pull/12

**Comment by zkat** [comment]
@ljharb lmao sorry. I forgot to fill it in after I posted the PR. Fixed 👍

**Review by iarna — APPROVED** [review]
🐑

**Comment by zkat** [comment]
@rarkins 
```
➜ npm view npm@latest repository
{ type: 'git', url: 'git+https://github.com/npm/cli.git' }
```
It seems to be fine now.

**Comment by rarkins** [comment]
@zkat I was meaning to reference the top-level field, e.g.

```
❯ curl --silent https://registry.npmjs.org/npm | jq -r '.repository'
{
  "type": "git",
  "url": "git+https://github.com/npm/npm.git"
}
```

This is what I have been using until now as the definitive source repository for a package.

Is there any reason why/when this shouldn't match exactly with the `repository` object inside the `latest` version?

**Pull request merged**
