### PR TITLE
deps updates

### PR DESCRIPTION
**Pull request by wraithgar**
- **deps!: init-package-json@8.0.0**
- **deps: walk-up-path@4.0.0**
- **deps: diff@7.0.0**
- **deps: p-map@7.0.2**
- **deps: node-gyp@11.0.0**
- **deps: @npmcli/run-script@9.0.2**

### CODE REVIEW

**Review by reggi — DISMISSED** [review]
esm strikes again

**Comment by lukekarrys** [comment]
`node-gyp@11.0.0` has just been published. The only change is to align `engines` with npm@10 and to update the dependencies that this allowed.

**Comment by wraithgar** [comment]
Thanks for the heads up @lukekarrys.  We'll hold off on today's release to wait on updating that.

**Comment by wraithgar** [comment]
v10 backport branch has the latest node-gyp https://github.com/npm/cli/pull/7957

**Review by reggi — APPROVED** [review]

**Review by reggi — APPROVED** [review]

**Pull request merged**
