### PR TITLE
docs: fix typos in definitions.js

### PR DESCRIPTION
**Pull request by ericmutta**
Fix a typo in the docs for the `--access` flag which shows up like this on the site:

image

The sentence *"If do not want..."* should read *"If **you** do not want..."*.

---
Fix a typo in the docs for the `--strict-peer-deps` flag which shows up like this on the site:

image

The sentence *"When such and override is performed"* should read *"When such **an** override is performed"*.

---
Fix a typo in the docs for the `--global-style` flag which shows up like this on the site:

image

The sentence *"...hoist on deeper dependendencies"* should read *"...hoist on deeper **dependencies**"*.

### CODE REVIEW

**Review by lukekarrys — APPROVED** [review]

**Comment by lukekarrys** [comment]
@ericmutta our docs are validated via snapshot testing. could you run `npm run snap` and commit the resulting changes? apologies that this process is not better documented 🙇🏼

**Review by lukekarrys — CHANGES_REQUESTED** [review]
Needs snapshot updates

**Comment by ericmutta** [comment]
> @lukekarrys could you run `npm run snap` and commit the resulting changes?

I made all the edits in this and other npm-related PRs via the GitHub editor, so I don't have a local setup where I can run that command. If there's a guide I can follow I am happy to try again...alternatively, in the interests of saving time, I am also OK if you were to fix the minor typos on your existing setup and commit that :+1: 

PS: kudos to you and the team for working on the NPM docs - they are easy to read and have turned me into "an NPM believer" :smile:

**Comment by lukekarrys** [comment]
Thank you @ericmutta! I took your commits and opened #6038 which also updates the snapshots.

**Comment by ericmutta** [comment]
Awesome @lukekarrys, many thanks! :fire:

**Pull request closed without merging**
